//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.cayantransportclient;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EbtAmountDetails complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="EbtAmountDetails">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="SnapAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="SnapTaxAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EbtAmountDetails", propOrder = {
    "snapAmount",
    "snapTaxAmount"
})
public class EbtAmountDetails {

    @XmlElement(name = "SnapAmount", required = true)
    protected BigDecimal snapAmount;
    @XmlElement(name = "SnapTaxAmount", required = true)
    protected BigDecimal snapTaxAmount;

    /**
     * Gets the value of the snapAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSnapAmount() {
        return snapAmount;
    }

    /**
     * Sets the value of the snapAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSnapAmount(BigDecimal value) {
        this.snapAmount = value;
    }

    /**
     * Gets the value of the snapTaxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSnapTaxAmount() {
        return snapTaxAmount;
    }

    /**
     * Sets the value of the snapTaxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSnapTaxAmount(BigDecimal value) {
        this.snapTaxAmount = value;
    }

}
