//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.cayantransportclient;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HealthCareAmountDetails complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="HealthCareAmountDetails">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="CopayAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="ClinicalAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="DentalAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="HealthCareTotalAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="PrescriptionAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         <element name="VisionAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HealthCareAmountDetails", propOrder = {
    "copayAmount",
    "clinicalAmount",
    "dentalAmount",
    "healthCareTotalAmount",
    "prescriptionAmount",
    "visionAmount"
})
public class HealthCareAmountDetails {

    @XmlElement(name = "CopayAmount", required = true)
    protected BigDecimal copayAmount;
    @XmlElement(name = "ClinicalAmount", required = true)
    protected BigDecimal clinicalAmount;
    @XmlElement(name = "DentalAmount", required = true)
    protected BigDecimal dentalAmount;
    @XmlElement(name = "HealthCareTotalAmount", required = true)
    protected BigDecimal healthCareTotalAmount;
    @XmlElement(name = "PrescriptionAmount", required = true)
    protected BigDecimal prescriptionAmount;
    @XmlElement(name = "VisionAmount", required = true)
    protected BigDecimal visionAmount;

    /**
     * Gets the value of the copayAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCopayAmount() {
        return copayAmount;
    }

    /**
     * Sets the value of the copayAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCopayAmount(BigDecimal value) {
        this.copayAmount = value;
    }

    /**
     * Gets the value of the clinicalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getClinicalAmount() {
        return clinicalAmount;
    }

    /**
     * Sets the value of the clinicalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setClinicalAmount(BigDecimal value) {
        this.clinicalAmount = value;
    }

    /**
     * Gets the value of the dentalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDentalAmount() {
        return dentalAmount;
    }

    /**
     * Sets the value of the dentalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDentalAmount(BigDecimal value) {
        this.dentalAmount = value;
    }

    /**
     * Gets the value of the healthCareTotalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHealthCareTotalAmount() {
        return healthCareTotalAmount;
    }

    /**
     * Sets the value of the healthCareTotalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHealthCareTotalAmount(BigDecimal value) {
        this.healthCareTotalAmount = value;
    }

    /**
     * Gets the value of the prescriptionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrescriptionAmount() {
        return prescriptionAmount;
    }

    /**
     * Sets the value of the prescriptionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrescriptionAmount(BigDecimal value) {
        this.prescriptionAmount = value;
    }

    /**
     * Gets the value of the visionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVisionAmount() {
        return visionAmount;
    }

    /**
     * Sets the value of the visionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVisionAmount(BigDecimal value) {
        this.visionAmount = value;
    }

}
