//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.cayanclient;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="AttachSignatureResult" type="{http://schemas.merchantwarehouse.com/merchantware/v45/}SignatureResponse45" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attachSignatureResult"
})
@XmlRootElement(name = "AttachSignatureResponse")
public class AttachSignatureResponse {

    @XmlElement(name = "AttachSignatureResult")
    protected SignatureResponse45 attachSignatureResult;

    /**
     * Gets the value of the attachSignatureResult property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureResponse45 }
     *     
     */
    public SignatureResponse45 getAttachSignatureResult() {
        return attachSignatureResult;
    }

    /**
     * Sets the value of the attachSignatureResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureResponse45 }
     *     
     */
    public void setAttachSignatureResult(SignatureResponse45 value) {
        this.attachSignatureResult = value;
    }

}
