//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.cayanclient;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Credentials" type="{http://schemas.merchantwarehouse.com/merchantware/v45/}MerchantCredentials" minOccurs="0"/>
 *         <element name="PaymentData" type="{http://schemas.merchantwarehouse.com/merchantware/v45/}PaymentData" minOccurs="0"/>
 *         <element name="Request" type="{http://schemas.merchantwarehouse.com/merchantware/v45/}BoardingRequest" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "credentials",
    "paymentData",
    "request"
})
@XmlRootElement(name = "BoardCard")
public class BoardCard {

    @XmlElement(name = "Credentials")
    protected MerchantCredentials credentials;
    @XmlElement(name = "PaymentData")
    protected PaymentData paymentData;
    @XmlElement(name = "Request")
    protected BoardingRequest request;

    /**
     * Gets the value of the credentials property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantCredentials }
     *     
     */
    public MerchantCredentials getCredentials() {
        return credentials;
    }

    /**
     * Sets the value of the credentials property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantCredentials }
     *     
     */
    public void setCredentials(MerchantCredentials value) {
        this.credentials = value;
    }

    /**
     * Gets the value of the paymentData property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentData }
     *     
     */
    public PaymentData getPaymentData() {
        return paymentData;
    }

    /**
     * Sets the value of the paymentData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentData }
     *     
     */
    public void setPaymentData(PaymentData value) {
        this.paymentData = value;
    }

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link BoardingRequest }
     *     
     */
    public BoardingRequest getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link BoardingRequest }
     *     
     */
    public void setRequest(BoardingRequest value) {
        this.request = value;
    }

}
