//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.28 at 02:15:16 PM IST 
//


package com.siteone.integration.webserviceclient.cayanclient;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ForceCaptureResult" type="{http://schemas.merchantwarehouse.com/merchantware/v45/}TransactionResponse45" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "forceCaptureResult"
})
@XmlRootElement(name = "ForceCaptureResponse")
public class ForceCaptureResponse {

    @XmlElement(name = "ForceCaptureResult")
    protected TransactionResponse45 forceCaptureResult;

    /**
     * Gets the value of the forceCaptureResult property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionResponse45 }
     *     
     */
    public TransactionResponse45 getForceCaptureResult() {
        return forceCaptureResult;
    }

    /**
     * Sets the value of the forceCaptureResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionResponse45 }
     *     
     */
    public void setForceCaptureResult(TransactionResponse45 value) {
        this.forceCaptureResult = value;
    }

}
