//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.cayanclient;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ForceCaptureRequest complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ForceCaptureRequest">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Amount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="AuthorizationCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="InvoiceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="RegisterNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="MerchantTransactionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="CardAcceptorTerminalId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="CardCaptureCapability" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="EcommerceTransactionIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="PinAuthenticationCapability" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="PosConditionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="PosEntryMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="TerminalCategoryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="TerminalEntryCapability" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="TerminalLocationIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ForceCaptureRequest", propOrder = {
    "amount",
    "authorizationCode",
    "invoiceNumber",
    "registerNumber",
    "merchantTransactionId",
    "cardAcceptorTerminalId",
    "cardCaptureCapability",
    "ecommerceTransactionIndicator",
    "pinAuthenticationCapability",
    "posConditionCode",
    "posEntryMode",
    "terminalCategoryCode",
    "terminalEntryCapability",
    "terminalLocationIndicator"
})
public class ForceCaptureRequest {

    @XmlElement(name = "Amount")
    protected String amount;
    @XmlElement(name = "AuthorizationCode")
    protected String authorizationCode;
    @XmlElement(name = "InvoiceNumber")
    protected String invoiceNumber;
    @XmlElement(name = "RegisterNumber")
    protected String registerNumber;
    @XmlElement(name = "MerchantTransactionId")
    protected String merchantTransactionId;
    @XmlElement(name = "CardAcceptorTerminalId")
    protected String cardAcceptorTerminalId;
    @XmlElement(name = "CardCaptureCapability")
    protected String cardCaptureCapability;
    @XmlElement(name = "EcommerceTransactionIndicator")
    protected String ecommerceTransactionIndicator;
    @XmlElement(name = "PinAuthenticationCapability")
    protected String pinAuthenticationCapability;
    @XmlElement(name = "PosConditionCode")
    protected String posConditionCode;
    @XmlElement(name = "PosEntryMode")
    protected String posEntryMode;
    @XmlElement(name = "TerminalCategoryCode")
    protected String terminalCategoryCode;
    @XmlElement(name = "TerminalEntryCapability")
    protected String terminalEntryCapability;
    @XmlElement(name = "TerminalLocationIndicator")
    protected String terminalLocationIndicator;

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmount(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the authorizationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizationCode() {
        return authorizationCode;
    }

    /**
     * Sets the value of the authorizationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizationCode(String value) {
        this.authorizationCode = value;
    }

    /**
     * Gets the value of the invoiceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceNumber(String value) {
        this.invoiceNumber = value;
    }

    /**
     * Gets the value of the registerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegisterNumber() {
        return registerNumber;
    }

    /**
     * Sets the value of the registerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegisterNumber(String value) {
        this.registerNumber = value;
    }

    /**
     * Gets the value of the merchantTransactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantTransactionId() {
        return merchantTransactionId;
    }

    /**
     * Sets the value of the merchantTransactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantTransactionId(String value) {
        this.merchantTransactionId = value;
    }

    /**
     * Gets the value of the cardAcceptorTerminalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardAcceptorTerminalId() {
        return cardAcceptorTerminalId;
    }

    /**
     * Sets the value of the cardAcceptorTerminalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardAcceptorTerminalId(String value) {
        this.cardAcceptorTerminalId = value;
    }

    /**
     * Gets the value of the cardCaptureCapability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardCaptureCapability() {
        return cardCaptureCapability;
    }

    /**
     * Sets the value of the cardCaptureCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardCaptureCapability(String value) {
        this.cardCaptureCapability = value;
    }

    /**
     * Gets the value of the ecommerceTransactionIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcommerceTransactionIndicator() {
        return ecommerceTransactionIndicator;
    }

    /**
     * Sets the value of the ecommerceTransactionIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcommerceTransactionIndicator(String value) {
        this.ecommerceTransactionIndicator = value;
    }

    /**
     * Gets the value of the pinAuthenticationCapability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinAuthenticationCapability() {
        return pinAuthenticationCapability;
    }

    /**
     * Sets the value of the pinAuthenticationCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinAuthenticationCapability(String value) {
        this.pinAuthenticationCapability = value;
    }

    /**
     * Gets the value of the posConditionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosConditionCode() {
        return posConditionCode;
    }

    /**
     * Sets the value of the posConditionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosConditionCode(String value) {
        this.posConditionCode = value;
    }

    /**
     * Gets the value of the posEntryMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosEntryMode() {
        return posEntryMode;
    }

    /**
     * Sets the value of the posEntryMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosEntryMode(String value) {
        this.posEntryMode = value;
    }

    /**
     * Gets the value of the terminalCategoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalCategoryCode() {
        return terminalCategoryCode;
    }

    /**
     * Sets the value of the terminalCategoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalCategoryCode(String value) {
        this.terminalCategoryCode = value;
    }

    /**
     * Gets the value of the terminalEntryCapability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalEntryCapability() {
        return terminalEntryCapability;
    }

    /**
     * Sets the value of the terminalEntryCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalEntryCapability(String value) {
        this.terminalEntryCapability = value;
    }

    /**
     * Gets the value of the terminalLocationIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalLocationIndicator() {
        return terminalLocationIndicator;
    }

    /**
     * Sets the value of the terminalLocationIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalLocationIndicator(String value) {
        this.terminalLocationIndicator = value;
    }

}
