//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.28 at 02:15:16 PM IST 
//


package com.siteone.integration.webserviceclient.cayanclient;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Source" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TrackData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PinBlock" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PinKsn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReaderEntryMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExpirationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardHolder" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AvsStreetAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AvsZipCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardVerificationValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Token" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VaultToken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="WalletId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EncryptedKeyedData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentCryptogram" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentCryptogramType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EncryptedPaymentData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EciIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentData", propOrder = {
    "source",
    "trackData",
    "pinBlock",
    "pinKsn",
    "readerEntryMode",
    "cardNumber",
    "expirationDate",
    "cardHolder",
    "avsStreetAddress",
    "avsZipCode",
    "cardVerificationValue",
    "token",
    "vaultToken",
    "walletId",
    "encryptedKeyedData",
    "paymentCryptogram",
    "paymentCryptogramType",
    "encryptedPaymentData",
    "eciIndicator"
})
public class PaymentData {

    @XmlElement(name = "Source")
    protected String source;
    @XmlElement(name = "TrackData")
    protected String trackData;
    @XmlElement(name = "PinBlock")
    protected String pinBlock;
    @XmlElement(name = "PinKsn")
    protected String pinKsn;
    @XmlElement(name = "ReaderEntryMode")
    protected String readerEntryMode;
    @XmlElement(name = "CardNumber")
    protected String cardNumber;
    @XmlElement(name = "ExpirationDate")
    protected String expirationDate;
    @XmlElement(name = "CardHolder")
    protected String cardHolder;
    @XmlElement(name = "AvsStreetAddress")
    protected String avsStreetAddress;
    @XmlElement(name = "AvsZipCode")
    protected String avsZipCode;
    @XmlElement(name = "CardVerificationValue")
    protected String cardVerificationValue;
    @XmlElement(name = "Token")
    protected String token;
    @XmlElement(name = "VaultToken")
    protected String vaultToken;
    @XmlElement(name = "WalletId")
    protected String walletId;
    @XmlElement(name = "EncryptedKeyedData")
    protected String encryptedKeyedData;
    @XmlElement(name = "PaymentCryptogram")
    protected String paymentCryptogram;
    @XmlElement(name = "PaymentCryptogramType")
    protected String paymentCryptogramType;
    @XmlElement(name = "EncryptedPaymentData")
    protected String encryptedPaymentData;
    @XmlElement(name = "EciIndicator")
    protected String eciIndicator;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the trackData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackData() {
        return trackData;
    }

    /**
     * Sets the value of the trackData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackData(String value) {
        this.trackData = value;
    }

    /**
     * Gets the value of the pinBlock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinBlock() {
        return pinBlock;
    }

    /**
     * Sets the value of the pinBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinBlock(String value) {
        this.pinBlock = value;
    }

    /**
     * Gets the value of the pinKsn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinKsn() {
        return pinKsn;
    }

    /**
     * Sets the value of the pinKsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinKsn(String value) {
        this.pinKsn = value;
    }

    /**
     * Gets the value of the readerEntryMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReaderEntryMode() {
        return readerEntryMode;
    }

    /**
     * Sets the value of the readerEntryMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReaderEntryMode(String value) {
        this.readerEntryMode = value;
    }

    /**
     * Gets the value of the cardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * Sets the value of the cardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardNumber(String value) {
        this.cardNumber = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpirationDate(String value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the cardHolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardHolder() {
        return cardHolder;
    }

    /**
     * Sets the value of the cardHolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardHolder(String value) {
        this.cardHolder = value;
    }

    /**
     * Gets the value of the avsStreetAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvsStreetAddress() {
        return avsStreetAddress;
    }

    /**
     * Sets the value of the avsStreetAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvsStreetAddress(String value) {
        this.avsStreetAddress = value;
    }

    /**
     * Gets the value of the avsZipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvsZipCode() {
        return avsZipCode;
    }

    /**
     * Sets the value of the avsZipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvsZipCode(String value) {
        this.avsZipCode = value;
    }

    /**
     * Gets the value of the cardVerificationValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardVerificationValue() {
        return cardVerificationValue;
    }

    /**
     * Sets the value of the cardVerificationValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardVerificationValue(String value) {
        this.cardVerificationValue = value;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the vaultToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVaultToken() {
        return vaultToken;
    }

    /**
     * Sets the value of the vaultToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVaultToken(String value) {
        this.vaultToken = value;
    }

    /**
     * Gets the value of the walletId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWalletId() {
        return walletId;
    }

    /**
     * Sets the value of the walletId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWalletId(String value) {
        this.walletId = value;
    }

    /**
     * Gets the value of the encryptedKeyedData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncryptedKeyedData() {
        return encryptedKeyedData;
    }

    /**
     * Sets the value of the encryptedKeyedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptedKeyedData(String value) {
        this.encryptedKeyedData = value;
    }

    /**
     * Gets the value of the paymentCryptogram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentCryptogram() {
        return paymentCryptogram;
    }

    /**
     * Sets the value of the paymentCryptogram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentCryptogram(String value) {
        this.paymentCryptogram = value;
    }

    /**
     * Gets the value of the paymentCryptogramType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentCryptogramType() {
        return paymentCryptogramType;
    }

    /**
     * Sets the value of the paymentCryptogramType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentCryptogramType(String value) {
        this.paymentCryptogramType = value;
    }

    /**
     * Gets the value of the encryptedPaymentData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncryptedPaymentData() {
        return encryptedPaymentData;
    }

    /**
     * Sets the value of the encryptedPaymentData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptedPaymentData(String value) {
        this.encryptedPaymentData = value;
    }

    /**
     * Gets the value of the eciIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEciIndicator() {
        return eciIndicator;
    }

    /**
     * Sets the value of the eciIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEciIndicator(String value) {
        this.eciIndicator = value;
    }

}
