//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The request used to pass Buyer Input Tax and Import Tax to the Tax Journal for return reporting.
 * 
 * <p>Java class for BuyerInputTaxRequestType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="BuyerInputTaxRequestType">
 *   <complexContent>
 *     <extension base="{urn:vertexinc:o-series:tps:9:0}TaxTransactionRequestType">
 *       <sequence>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}Currency" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}OriginalCurrency" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}CompanyCodeCurrency" minOccurs="0"/>
 *         <element name="Buyer" type="{urn:vertexinc:o-series:tps:9:0}BuyerType" minOccurs="0"/>
 *         <element name="Vendor" type="{urn:vertexinc:o-series:tps:9:0}VendorType" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}ProratePercentage" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}CurrencyConversionFactors" minOccurs="0"/>
 *         <element name="LineItem" maxOccurs="unbounded">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{urn:vertexinc:o-series:tps:9:0}LineItemBITIType">
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *       <attGroup ref="{urn:vertexinc:o-series:tps:9:0}BuyerInputTaxTransactionGroup"/>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BuyerInputTaxRequestType", propOrder = {
    "currency",
    "originalCurrency",
    "companyCodeCurrency",
    "buyer",
    "vendor",
    "proratePercentage",
    "currencyConversionFactors",
    "lineItem"
})
public class BuyerInputTaxRequestType
    extends TaxTransactionRequestType
{

    /**
     * Default unit of currency for the entire transaction.
     * 
     */
    @XmlElement(name = "Currency")
    protected CurrencyType currency;
    /**
     * This represents the currency in which the original business transaction took place.
     * 
     */
    @XmlElement(name = "OriginalCurrency")
    protected CurrencyType originalCurrency;
    /**
     * The default currency code of the company that is integrated with the ERP or host system.
     *                 O Series does not use this field in tax calculations.
     * 
     */
    @XmlElement(name = "CompanyCodeCurrency")
    protected CurrencyType companyCodeCurrency;
    /**
     * The buyer for the transaction. The buyer is described by the child elements and attributes.
     * 
     */
    @XmlElement(name = "Buyer")
    protected BuyerType buyer;
    /**
     * The vendor for the transaction. The vendor is described by the child elements and attributes.
     * 
     */
    @XmlElement(name = "Vendor")
    protected VendorType vendor;
    /**
     * Percentage passed from the billing system to calculate a remainder of an assessed tax or fee.
     * 
     */
    @XmlElement(name = "ProratePercentage")
    protected BigDecimal proratePercentage;
    /**
     * A list of conversion factors that Vertex O Series requires to perform currency conversion. These factors include Source Currency, Target Currency, and Conversion Factor.
     * 
     */
    @XmlElement(name = "CurrencyConversionFactors")
    protected CurrencyConversionFactors currencyConversionFactors;
    /**
     * The header for a component of a transaction.  A line item is required for each component of the transaction. Each transaction requires at least one line item.
     * 
     */
    @XmlElement(name = "LineItem", required = true)
    protected List<BuyerInputTaxRequestType.LineItem> lineItem;
    /**
     * The document number in the host application that references the event.
     * 
     */
    @XmlAttribute(name = "documentNumber")
    protected String documentNumber;
    /**
     * A string to represent the accumulation invoice identity.
     * 
     */
    @XmlAttribute(name = "accumulationDocumentNumber")
    protected String accumulationDocumentNumber;
    /**
     * A string to represent the accumulation customer identity.
     * 
     */
    @XmlAttribute(name = "accumulationCustomerNumber")
    protected String accumulationCustomerNumber;
    /**
     * Indicates the type of business transaction to be posted. This field is on the transaction level.
     * 
     */
    @XmlAttribute(name = "documentType")
    protected String documentType;
    /**
     * Indicates the billing documents that specify different business transactions that are involved in billing activities. Examples of billing documents include  invoice, credit or debit memo, or cancellation document. This field is on the transaction level.
     * 
     */
    @XmlAttribute(name = "billingType")
    protected String billingType;
    /**
     * The key that identifies the purpose of the order. This field is on the transaction level.
     * 
     */
    @XmlAttribute(name = "orderType")
    protected String orderType;
    /**
     * The date when the transaction is posted for auditing and reporting purposes. If no date is provided, the Calculation Engine uses the date when the transaction was processed.
     * 
     */
    @XmlAttribute(name = "postingDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar postingDate;
    /**
     * A value that can be used for tax return filing in jurisdictions that require taxes to be filed for individual retail locations.
     * 
     */
    @XmlAttribute(name = "locationCode")
    protected String locationCode;
    /**
     * Indicates whether the response message should contain an additional structure that shows the elements/attributes that were changed by Tax Assist. This is for informational purposes only and contains no tax results.
     * 
     */
    @XmlAttribute(name = "returnAssistedParametersIndicator")
    protected Boolean returnAssistedParametersIndicator;
    /**
     * If this indicator is set, the response message returns child line items that were generated by the Tax Assist allocation feature. Otherwise, these line items are deleted after the transaction is written to the Tax Journal and only the primary line item, which contains the combined tax results of the child line items, is passed back to the host system.
     * 
     */
    @XmlAttribute(name = "returnGeneratedLineItemsIndicator")
    protected Boolean returnGeneratedLineItemsIndicator;
    /**
     * An identifier that determines the vendor or customer jurisdiction in which the title transfer of a supply takes place. This is also known as Shipping Terms. Delivery Terms information could be critical to determine the place of supply, for example, in distance selling.
     * 
     */
    @XmlAttribute(name = "deliveryTerm")
    protected DeliveryTermCodeType deliveryTerm;
    /**
     * The actual date of the requested action. The calculation engine uses this date to determine the valid tax rates and rules.
     * 
     */
    @XmlAttribute(name = "documentDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar documentDate;
    /**
     * An identifier that further defines the document and corresponds to the transaction stored in the host system. The Transaction ID is used for synchronization services, but is not used for reporting purposes.
     * 
     */
    @XmlAttribute(name = "transactionId")
    protected String transactionId;
    /**
     * The date used to calculate Recoverable Input VAT.
     * 
     */
    @XmlAttribute(name = "recoverableDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar recoverableDate;
    /**
     * Indicates whether the results of the transaction are written to the Tax Journal. Defaults to true.
     * 
     */
    @XmlAttribute(name = "postToJournal")
    protected Boolean postToJournal;
    /**
     * The roundAtLineLevel attribute enables you to apply line-item level or invoice-level rounding to tax calculations. Set this attribute to True to set up line-item level rounding. With line-item level rounding, the Calculation Engine rounds amounts at the line-item level and then sums those amounts to calculate an invoice total. This method is useful for invoices that include line items with different taxing jurisdictions.
     * 
     * The default value for this attribute is False. In this case, O Series applies an invoice-level rounding, where the Calculation Engine compares the sum of rounded line item-level totals to the rounded invoice-level total. When there is a difference between these totals, the Calculation Engine compares differences between rounded and unrounded amounts at each jurisdiction level and distributes the difference to the jurisdiction that results in the smallest total rounding difference amount. For more information about invoice-level rounding, contact Vertex Product Support to obtain the Rounding Guide.
     * 
     */
    @XmlAttribute(name = "roundAtLineLevel")
    protected Boolean roundAtLineLevel;
    /**
     * The date the purchaser paid for the product. If the purchaser pays for the product but physically receives it at a later date, Vertex O Series uses this field for returns and reporting for your tax type.  This field is also used in cash accounting.
     * 
     */
    @XmlAttribute(name = "paymentDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar paymentDate;
    /**
     * Supports reporting and the document sequence identifier used by your ERP system. Some countries require that documents follow a unique sequential sequence number, depending on the registration type and the type of invoice. Use this field for audit purposes to track the sequence of your documents. This field is used in European Union (EU) countries.
     * 
     */
    @XmlAttribute(name = "documentSequenceId")
    protected String documentSequenceId;
    /**
     * The date that drives the timing of when the VAT liability arises. In some countries, if the Tax Point Date, (also called the Time of Supply) is different from the invoice date, this field is shown separately on an invoice. Use this field if you have reporting compliance in Spain, Poland, and Hungary.
     * 
     */
    @XmlAttribute(name = "taxPointDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar taxPointDate;

    /**
     * Default unit of currency for the entire transaction.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyType }
     *     
     */
    public CurrencyType getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyType }
     *     
     * @see #getCurrency()
     */
    public void setCurrency(CurrencyType value) {
        this.currency = value;
    }

    /**
     * This represents the currency in which the original business transaction took place.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyType }
     *     
     */
    public CurrencyType getOriginalCurrency() {
        return originalCurrency;
    }

    /**
     * Sets the value of the originalCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyType }
     *     
     * @see #getOriginalCurrency()
     */
    public void setOriginalCurrency(CurrencyType value) {
        this.originalCurrency = value;
    }

    /**
     * The default currency code of the company that is integrated with the ERP or host system.
     *                 O Series does not use this field in tax calculations.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyType }
     *     
     */
    public CurrencyType getCompanyCodeCurrency() {
        return companyCodeCurrency;
    }

    /**
     * Sets the value of the companyCodeCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyType }
     *     
     * @see #getCompanyCodeCurrency()
     */
    public void setCompanyCodeCurrency(CurrencyType value) {
        this.companyCodeCurrency = value;
    }

    /**
     * The buyer for the transaction. The buyer is described by the child elements and attributes.
     * 
     * @return
     *     possible object is
     *     {@link BuyerType }
     *     
     */
    public BuyerType getBuyer() {
        return buyer;
    }

    /**
     * Sets the value of the buyer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuyerType }
     *     
     * @see #getBuyer()
     */
    public void setBuyer(BuyerType value) {
        this.buyer = value;
    }

    /**
     * The vendor for the transaction. The vendor is described by the child elements and attributes.
     * 
     * @return
     *     possible object is
     *     {@link VendorType }
     *     
     */
    public VendorType getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorType }
     *     
     * @see #getVendor()
     */
    public void setVendor(VendorType value) {
        this.vendor = value;
    }

    /**
     * Percentage passed from the billing system to calculate a remainder of an assessed tax or fee.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProratePercentage() {
        return proratePercentage;
    }

    /**
     * Sets the value of the proratePercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getProratePercentage()
     */
    public void setProratePercentage(BigDecimal value) {
        this.proratePercentage = value;
    }

    /**
     * A list of conversion factors that Vertex O Series requires to perform currency conversion. These factors include Source Currency, Target Currency, and Conversion Factor.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyConversionFactors }
     *     
     */
    public CurrencyConversionFactors getCurrencyConversionFactors() {
        return currencyConversionFactors;
    }

    /**
     * Sets the value of the currencyConversionFactors property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyConversionFactors }
     *     
     * @see #getCurrencyConversionFactors()
     */
    public void setCurrencyConversionFactors(CurrencyConversionFactors value) {
        this.currencyConversionFactors = value;
    }

    /**
     * The header for a component of a transaction.  A line item is required for each component of the transaction. Each transaction requires at least one line item.
     * 
     * Gets the value of the lineItem property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineItem property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getLineItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BuyerInputTaxRequestType.LineItem }
     * </p>
     * 
     * 
     * @return
     *     The value of the lineItem property.
     */
    public List<BuyerInputTaxRequestType.LineItem> getLineItem() {
        if (lineItem == null) {
            lineItem = new ArrayList<>();
        }
        return this.lineItem;
    }

    /**
     * The document number in the host application that references the event.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentNumber() {
        return documentNumber;
    }

    /**
     * Sets the value of the documentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDocumentNumber()
     */
    public void setDocumentNumber(String value) {
        this.documentNumber = value;
    }

    /**
     * A string to represent the accumulation invoice identity.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccumulationDocumentNumber() {
        return accumulationDocumentNumber;
    }

    /**
     * Sets the value of the accumulationDocumentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getAccumulationDocumentNumber()
     */
    public void setAccumulationDocumentNumber(String value) {
        this.accumulationDocumentNumber = value;
    }

    /**
     * A string to represent the accumulation customer identity.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccumulationCustomerNumber() {
        return accumulationCustomerNumber;
    }

    /**
     * Sets the value of the accumulationCustomerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getAccumulationCustomerNumber()
     */
    public void setAccumulationCustomerNumber(String value) {
        this.accumulationCustomerNumber = value;
    }

    /**
     * Indicates the type of business transaction to be posted. This field is on the transaction level.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDocumentType()
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Indicates the billing documents that specify different business transactions that are involved in billing activities. Examples of billing documents include  invoice, credit or debit memo, or cancellation document. This field is on the transaction level.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingType() {
        return billingType;
    }

    /**
     * Sets the value of the billingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getBillingType()
     */
    public void setBillingType(String value) {
        this.billingType = value;
    }

    /**
     * The key that identifies the purpose of the order. This field is on the transaction level.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getOrderType()
     */
    public void setOrderType(String value) {
        this.orderType = value;
    }

    /**
     * The date when the transaction is posted for auditing and reporting purposes. If no date is provided, the Calculation Engine uses the date when the transaction was processed.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPostingDate() {
        return postingDate;
    }

    /**
     * Sets the value of the postingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getPostingDate()
     */
    public void setPostingDate(XMLGregorianCalendar value) {
        this.postingDate = value;
    }

    /**
     * A value that can be used for tax return filing in jurisdictions that require taxes to be filed for individual retail locations.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationCode() {
        return locationCode;
    }

    /**
     * Sets the value of the locationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getLocationCode()
     */
    public void setLocationCode(String value) {
        this.locationCode = value;
    }

    /**
     * Indicates whether the response message should contain an additional structure that shows the elements/attributes that were changed by Tax Assist. This is for informational purposes only and contains no tax results.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReturnAssistedParametersIndicator() {
        return returnAssistedParametersIndicator;
    }

    /**
     * Sets the value of the returnAssistedParametersIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #isReturnAssistedParametersIndicator()
     */
    public void setReturnAssistedParametersIndicator(Boolean value) {
        this.returnAssistedParametersIndicator = value;
    }

    /**
     * If this indicator is set, the response message returns child line items that were generated by the Tax Assist allocation feature. Otherwise, these line items are deleted after the transaction is written to the Tax Journal and only the primary line item, which contains the combined tax results of the child line items, is passed back to the host system.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReturnGeneratedLineItemsIndicator() {
        return returnGeneratedLineItemsIndicator;
    }

    /**
     * Sets the value of the returnGeneratedLineItemsIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #isReturnGeneratedLineItemsIndicator()
     */
    public void setReturnGeneratedLineItemsIndicator(Boolean value) {
        this.returnGeneratedLineItemsIndicator = value;
    }

    /**
     * An identifier that determines the vendor or customer jurisdiction in which the title transfer of a supply takes place. This is also known as Shipping Terms. Delivery Terms information could be critical to determine the place of supply, for example, in distance selling.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryTermCodeType }
     *     
     */
    public DeliveryTermCodeType getDeliveryTerm() {
        return deliveryTerm;
    }

    /**
     * Sets the value of the deliveryTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryTermCodeType }
     *     
     * @see #getDeliveryTerm()
     */
    public void setDeliveryTerm(DeliveryTermCodeType value) {
        this.deliveryTerm = value;
    }

    /**
     * The actual date of the requested action. The calculation engine uses this date to determine the valid tax rates and rules.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDocumentDate() {
        return documentDate;
    }

    /**
     * Sets the value of the documentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getDocumentDate()
     */
    public void setDocumentDate(XMLGregorianCalendar value) {
        this.documentDate = value;
    }

    /**
     * An identifier that further defines the document and corresponds to the transaction stored in the host system. The Transaction ID is used for synchronization services, but is not used for reporting purposes.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getTransactionId()
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * The date used to calculate Recoverable Input VAT.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRecoverableDate() {
        return recoverableDate;
    }

    /**
     * Sets the value of the recoverableDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getRecoverableDate()
     */
    public void setRecoverableDate(XMLGregorianCalendar value) {
        this.recoverableDate = value;
    }

    /**
     * Indicates whether the results of the transaction are written to the Tax Journal. Defaults to true.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPostToJournal() {
        if (postToJournal == null) {
            return true;
        } else {
            return postToJournal;
        }
    }

    /**
     * Sets the value of the postToJournal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #isPostToJournal()
     */
    public void setPostToJournal(Boolean value) {
        this.postToJournal = value;
    }

    /**
     * The roundAtLineLevel attribute enables you to apply line-item level or invoice-level rounding to tax calculations. Set this attribute to True to set up line-item level rounding. With line-item level rounding, the Calculation Engine rounds amounts at the line-item level and then sums those amounts to calculate an invoice total. This method is useful for invoices that include line items with different taxing jurisdictions.
     * 
     * The default value for this attribute is False. In this case, O Series applies an invoice-level rounding, where the Calculation Engine compares the sum of rounded line item-level totals to the rounded invoice-level total. When there is a difference between these totals, the Calculation Engine compares differences between rounded and unrounded amounts at each jurisdiction level and distributes the difference to the jurisdiction that results in the smallest total rounding difference amount. For more information about invoice-level rounding, contact Vertex Product Support to obtain the Rounding Guide.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRoundAtLineLevel() {
        return roundAtLineLevel;
    }

    /**
     * Sets the value of the roundAtLineLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #isRoundAtLineLevel()
     */
    public void setRoundAtLineLevel(Boolean value) {
        this.roundAtLineLevel = value;
    }

    /**
     * The date the purchaser paid for the product. If the purchaser pays for the product but physically receives it at a later date, Vertex O Series uses this field for returns and reporting for your tax type.  This field is also used in cash accounting.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPaymentDate() {
        return paymentDate;
    }

    /**
     * Sets the value of the paymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getPaymentDate()
     */
    public void setPaymentDate(XMLGregorianCalendar value) {
        this.paymentDate = value;
    }

    /**
     * Supports reporting and the document sequence identifier used by your ERP system. Some countries require that documents follow a unique sequential sequence number, depending on the registration type and the type of invoice. Use this field for audit purposes to track the sequence of your documents. This field is used in European Union (EU) countries.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentSequenceId() {
        return documentSequenceId;
    }

    /**
     * Sets the value of the documentSequenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDocumentSequenceId()
     */
    public void setDocumentSequenceId(String value) {
        this.documentSequenceId = value;
    }

    /**
     * The date that drives the timing of when the VAT liability arises. In some countries, if the Tax Point Date, (also called the Time of Supply) is different from the invoice date, this field is shown separately on an invoice. Use this field if you have reporting compliance in Spain, Poland, and Hungary.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTaxPointDate() {
        return taxPointDate;
    }

    /**
     * Sets the value of the taxPointDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getTaxPointDate()
     */
    public void setTaxPointDate(XMLGregorianCalendar value) {
        this.taxPointDate = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <extension base="{urn:vertexinc:o-series:tps:9:0}LineItemBITIType">
     *     </extension>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class LineItem
        extends LineItemBITIType
    {


    }

}
