//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Chain Transaction Phase identifies a phase within a series of transactions in which
 *                 multiple invoices are created with only a single movement of goods.
 *                 The phase identifies the position of the transaction in a supply chain. Use Tax Assist rules to evaluate
 *                 this indicator along with other transaction facts to set the title transfer value and determine an
 *                 appropriate taxability conclusion.
 * 
 * <p>Java class for ChainTransactionPhaseCodeType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="ChainTransactionPhaseCodeType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     <enumeration value="MANUFACTURER"/>
 *     <enumeration value="INTERMEDIARY"/>
 *     <enumeration value="FINAL"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ChainTransactionPhaseCodeType")
@XmlEnum
public enum ChainTransactionPhaseCodeType {


    /**
     * An entity that creates some good or tangible property.
     * 
     */
    MANUFACTURER,

    /**
     * A third-party entity between the manufacturer that creates the good or tangible
     *                         property and the final consumer of the good or property. This is a Domestic VAT scenario.
     * 
     */
    INTERMEDIARY,

    /**
     * An entity that is the final consumer of the good or tangible property. This is an
     *                         Intra-EU, Zero Rate VAT scenario.
     * 
     */
    FINAL;

    public String value() {
        return name();
    }

    public static ChainTransactionPhaseCodeType fromValue(String v) {
        return valueOf(v);
    }

}
