//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Copyright Vertex Inc. 2007-2012 All Rights Reserved
 * 
 * <p>Java class for CurrencyAmountType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="CurrencyAmountType">
 *   <simpleContent>
 *     <extension base="<http://www.w3.org/2001/XMLSchema>decimal">
 *       <attGroup ref="{urn:vertexinc:o-series:tps:9:0}isoCurrencyCode"/>
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CurrencyAmountType", propOrder = {
    "value"
})
public class CurrencyAmountType {

    @XmlValue
    protected BigDecimal value;
    /**
     * The ISO 4217 name for the currency unit. Not used for this version of O Series.
     * 
     */
    @XmlAttribute(name = "isoCurrencyName")
    protected String isoCurrencyName;
    /**
     * The three-character ISO 4217 alphabetic code for the currency unit.
     * 
     */
    @XmlAttribute(name = "isoCurrencyCodeAlpha")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isoCurrencyCodeAlpha;
    /**
     * The three-digit ISO 4217 numeric code for the currency unit.
     * 
     */
    @XmlAttribute(name = "isoCurrencyCodeNum")
    protected Integer isoCurrencyCodeNum;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    /**
     * The ISO 4217 name for the currency unit. Not used for this version of O Series.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsoCurrencyName() {
        return isoCurrencyName;
    }

    /**
     * Sets the value of the isoCurrencyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getIsoCurrencyName()
     */
    public void setIsoCurrencyName(String value) {
        this.isoCurrencyName = value;
    }

    /**
     * The three-character ISO 4217 alphabetic code for the currency unit.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsoCurrencyCodeAlpha() {
        return isoCurrencyCodeAlpha;
    }

    /**
     * Sets the value of the isoCurrencyCodeAlpha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getIsoCurrencyCodeAlpha()
     */
    public void setIsoCurrencyCodeAlpha(String value) {
        this.isoCurrencyCodeAlpha = value;
    }

    /**
     * The three-digit ISO 4217 numeric code for the currency unit.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIsoCurrencyCodeNum() {
        return isoCurrencyCodeNum;
    }

    /**
     * Sets the value of the isoCurrencyCodeNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getIsoCurrencyCodeNum()
     */
    public void setIsoCurrencyCodeNum(Integer value) {
        this.isoCurrencyCodeNum = value;
    }

}
