//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}DispatcherCode"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}TaxRegistration" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dispatcherCode",
    "taxRegistration"
})
@XmlRootElement(name = "Dispatcher")
public class Dispatcher {

    /**
     * A user-defined code that represents the dispatcher for the transaction or line item.
     * 
     */
    @XmlElement(name = "DispatcherCode", required = true)
    protected DispatcherCode dispatcherCode;
    /**
     * The Registration information for Value Added Tax. The transaction is considered to be a
     *                 VAT Group transaction if the Buyer and Seller have the same registration number, the Place of Supply
     *                 (POS) jurisdiction is an EU member country, and the InvoiceTaxCode is 2 (Intra-EU Notice).
     * 
     */
    @XmlElement(name = "TaxRegistration")
    protected List<TaxRegistrationType> taxRegistration;

    /**
     * A user-defined code that represents the dispatcher for the transaction or line item.
     * 
     * @return
     *     possible object is
     *     {@link DispatcherCode }
     *     
     */
    public DispatcherCode getDispatcherCode() {
        return dispatcherCode;
    }

    /**
     * Sets the value of the dispatcherCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link DispatcherCode }
     *     
     * @see #getDispatcherCode()
     */
    public void setDispatcherCode(DispatcherCode value) {
        this.dispatcherCode = value;
    }

    /**
     * The Registration information for Value Added Tax. The transaction is considered to be a
     *                 VAT Group transaction if the Buyer and Seller have the same registration number, the Place of Supply
     *                 (POS) jurisdiction is an EU member country, and the InvoiceTaxCode is 2 (Intra-EU Notice).
     * 
     * Gets the value of the taxRegistration property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxRegistration property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getTaxRegistration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxRegistrationType }
     * </p>
     * 
     * 
     * @return
     *     The value of the taxRegistration property.
     */
    public List<TaxRegistrationType> getTaxRegistration() {
        if (taxRegistration == null) {
            taxRegistration = new ArrayList<>();
        }
        return this.taxRegistration;
    }

}
