//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.28 at 02:15:16 PM IST 
//


package com.siteone.integration.webserviceclient.vertexclient;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FindTaxAreasRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FindTaxAreasRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:vertexinc:o-series:tps:9:0}TaxgisRequestType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TaxAreaLookup" type="{urn:vertexinc:o-series:tps:9:0}TaxAreaLookupType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FindTaxAreasRequestType", propOrder = {
    "taxAreaLookup"
})
public class FindTaxAreasRequestType
    extends TaxgisRequestType
{

    @XmlElement(name = "TaxAreaLookup", required = true)
    protected List<TaxAreaLookupType> taxAreaLookup;

    /**
     * Gets the value of the taxAreaLookup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxAreaLookup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxAreaLookup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxAreaLookupType }
     * 
     * 
     */
    public List<TaxAreaLookupType> getTaxAreaLookup() {
        if (taxAreaLookup == null) {
            taxAreaLookup = new ArrayList<>();
        }
        return this.taxAreaLookup;
    }

}
