//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Tax Area Response type structure
 * 
 * <p>Java class for FindTaxAreasResponseType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="FindTaxAreasResponseType">
 *   <complexContent>
 *     <extension base="{urn:vertexinc:o-series:tps:9:0}TaxgisResponseType">
 *       <sequence>
 *         <element name="TaxAreaLookupResult" type="{urn:vertexinc:o-series:tps:9:0}TaxAreaLookupResultType" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FindTaxAreasResponseType", propOrder = {
    "taxAreaLookupResult"
})
public class FindTaxAreasResponseType
    extends TaxgisResponseType
{

    /**
     * The results returned from the tax area lookup.
     * 
     */
    @XmlElement(name = "TaxAreaLookupResult")
    protected List<TaxAreaLookupResultType> taxAreaLookupResult;

    /**
     * The results returned from the tax area lookup.
     * 
     * Gets the value of the taxAreaLookupResult property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxAreaLookupResult property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getTaxAreaLookupResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxAreaLookupResultType }
     * </p>
     * 
     * 
     * @return
     *     The value of the taxAreaLookupResult property.
     */
    public List<TaxAreaLookupResultType> getTaxAreaLookupResult() {
        if (taxAreaLookupResult == null) {
            taxAreaLookupResult = new ArrayList<>();
        }
        return this.taxAreaLookupResult;
    }

}
