//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FindChangedTaxAreaIdsRequestType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="FindChangedTaxAreaIdsRequestType">
 *   <complexContent>
 *     <extension base="{urn:vertexinc:o-series:tps:9:0}TaxgisRequestType">
 *       <sequence>
 *         <element name="DatePeriod">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{urn:vertexinc:o-series:tps:9:0}DatePeriodType">
 *                 <sequence>
 *                   <element name="BeginDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   <element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FindChangedTaxAreaIdsRequestType", propOrder = {
    "datePeriod"
})
public class FindChangedTaxAreaIdsRequestType
    extends TaxgisRequestType
{

    /**
     * The date range to be searched.
     * 
     */
    @XmlElement(name = "DatePeriod", required = true)
    protected FindChangedTaxAreaIdsRequestType.DatePeriod datePeriod;

    /**
     * The date range to be searched.
     * 
     * @return
     *     possible object is
     *     {@link FindChangedTaxAreaIdsRequestType.DatePeriod }
     *     
     */
    public FindChangedTaxAreaIdsRequestType.DatePeriod getDatePeriod() {
        return datePeriod;
    }

    /**
     * Sets the value of the datePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link FindChangedTaxAreaIdsRequestType.DatePeriod }
     *     
     * @see #getDatePeriod()
     */
    public void setDatePeriod(FindChangedTaxAreaIdsRequestType.DatePeriod value) {
        this.datePeriod = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{urn:vertexinc:o-series:tps:9:0}DatePeriodType">
     *       <sequence>
     *         <element name="BeginDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         <element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DatePeriod
        extends DatePeriodType
    {


    }

}
