//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="TaxingJurisdictionLocation">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{urn:vertexinc:o-series:tps:9:0}TaxingJurisdictionLocationType">
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}InputAmount"/>
 *         <element name="InvoiceTaxRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         <element name="BlockingOverridePercent" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{urn:vertexinc:o-series:tps:9:0}PercentType">
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="PartialExemptRecoverableOverridePercent" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{urn:vertexinc:o-series:tps:9:0}PercentType">
 *             </restriction>
 *           </simpleType>
 *         </element>
 *       </sequence>
 *       <attribute name="isImport" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "taxingJurisdictionLocation",
    "inputAmount",
    "invoiceTaxRate",
    "blockingOverridePercent",
    "partialExemptRecoverableOverridePercent"
})
@XmlRootElement(name = "InputTax")
public class InputTax {

    /**
     * Identifies the jurisdiction where the tax is reported.
     * 
     */
    @XmlElement(name = "TaxingJurisdictionLocation", required = true)
    protected InputTax.TaxingJurisdictionLocation taxingJurisdictionLocation;
    /**
     * The amount of Input Tax to be distributed. Negative numbers are permitted so that
     *                 corrections may be processed
     * 
     */
    @XmlElement(name = "InputAmount", required = true)
    protected BigDecimal inputAmount;
    /**
     * The tax rate as shown on the vendor invoice.
     * 
     */
    @XmlElement(name = "InvoiceTaxRate")
    protected BigDecimal invoiceTaxRate;
    /**
     * The recoverable override percentage of the blocking override on the Input Tax
     *                             level.
     * 
     */
    @XmlElement(name = "BlockingOverridePercent")
    protected BigDecimal blockingOverridePercent;
    /**
     * The recoverable percentage
     *                             of a partial exemption. This field is populated only for transactions
     *                             with a tax type of Value Added Tax.
     * 
     */
    @XmlElement(name = "PartialExemptRecoverableOverridePercent")
    protected BigDecimal partialExemptRecoverableOverridePercent;
    /**
     * Indicates that the input tax is Import VAT. Defaults to false.
     * 
     */
    @XmlAttribute(name = "isImport")
    protected Boolean isImport;

    /**
     * Identifies the jurisdiction where the tax is reported.
     * 
     * @return
     *     possible object is
     *     {@link InputTax.TaxingJurisdictionLocation }
     *     
     */
    public InputTax.TaxingJurisdictionLocation getTaxingJurisdictionLocation() {
        return taxingJurisdictionLocation;
    }

    /**
     * Sets the value of the taxingJurisdictionLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputTax.TaxingJurisdictionLocation }
     *     
     * @see #getTaxingJurisdictionLocation()
     */
    public void setTaxingJurisdictionLocation(InputTax.TaxingJurisdictionLocation value) {
        this.taxingJurisdictionLocation = value;
    }

    /**
     * The amount of Input Tax to be distributed. Negative numbers are permitted so that
     *                 corrections may be processed
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInputAmount() {
        return inputAmount;
    }

    /**
     * Sets the value of the inputAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getInputAmount()
     */
    public void setInputAmount(BigDecimal value) {
        this.inputAmount = value;
    }

    /**
     * The tax rate as shown on the vendor invoice.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInvoiceTaxRate() {
        return invoiceTaxRate;
    }

    /**
     * Sets the value of the invoiceTaxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getInvoiceTaxRate()
     */
    public void setInvoiceTaxRate(BigDecimal value) {
        this.invoiceTaxRate = value;
    }

    /**
     * The recoverable override percentage of the blocking override on the Input Tax
     *                             level.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBlockingOverridePercent() {
        return blockingOverridePercent;
    }

    /**
     * Sets the value of the blockingOverridePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getBlockingOverridePercent()
     */
    public void setBlockingOverridePercent(BigDecimal value) {
        this.blockingOverridePercent = value;
    }

    /**
     * The recoverable percentage
     *                             of a partial exemption. This field is populated only for transactions
     *                             with a tax type of Value Added Tax.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPartialExemptRecoverableOverridePercent() {
        return partialExemptRecoverableOverridePercent;
    }

    /**
     * Sets the value of the partialExemptRecoverableOverridePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getPartialExemptRecoverableOverridePercent()
     */
    public void setPartialExemptRecoverableOverridePercent(BigDecimal value) {
        this.partialExemptRecoverableOverridePercent = value;
    }

    /**
     * Indicates that the input tax is Import VAT. Defaults to false.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsImport() {
        if (isImport == null) {
            return false;
        } else {
            return isImport;
        }
    }

    /**
     * Sets the value of the isImport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #isIsImport()
     */
    public void setIsImport(Boolean value) {
        this.isImport = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <extension base="{urn:vertexinc:o-series:tps:9:0}TaxingJurisdictionLocationType">
     *     </extension>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class TaxingJurisdictionLocation
        extends TaxingJurisdictionLocationType
    {


    }

}
