//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Copyright Vertex Inc. 2007-2012 All Rights Reserved
 * 
 * <p>Java class for JurisdictionLevelCodeType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="JurisdictionLevelCodeType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     <minLength value="1"/>
 *     <maxLength value="60"/>
 *     <enumeration value="APO"/>
 *     <enumeration value="BOROUGH"/>
 *     <enumeration value="CITY"/>
 *     <enumeration value="COUNTRY"/>
 *     <enumeration value="COUNTY"/>
 *     <enumeration value="DISTRICT"/>
 *     <enumeration value="FPO"/>
 *     <enumeration value="LOCAL_IMPROVEMENT_DISTRICT"/>
 *     <enumeration value="PARISH"/>
 *     <enumeration value="PROVINCE"/>
 *     <enumeration value="SPECIAL_PURPOSE_DISTRICT"/>
 *     <enumeration value="STATE"/>
 *     <enumeration value="TERRITORY"/>
 *     <enumeration value="TOWNSHIP"/>
 *     <enumeration value="TRADE_BLOCK"/>
 *     <enumeration value="TRANSIT_DISTRICT"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "JurisdictionLevelCodeType")
@XmlEnum
public enum JurisdictionLevelCodeType {


    /**
     * Army and Air Force Post Office box. This value may also be used for Diplomatic Post Office (DPO) box.
     * 
     */
    APO,

    /**
     * An entity that acts as a self-governing body on the local level.
     * 
     */
    BOROUGH,

    /**
     * An incorporated municipality in which definite boundaries and legal powers are set forth in a charter granted by the state.
     * 
     */
    CITY,

    /**
     * An entity that acts as a self-governing body, based on a special common geographic area of interest
     * 
     */
    COUNTRY,

    /**
     * An entity within a state or country, used for administrative purposes, created by territorial division for the purpose of local government.
     * 
     */
    COUNTY,

    /**
     * A local jurisdiction, which may or may not follow city or county boundaries, in which taxes or fees are imposed to benefit a specific purpose.  Examples include Special Purpose Districts, Municipal Transportation Authorities, Transit Districts, Community Improvement Districts, Transportation Development Districts, Hospital Districts, Local Improvement Districts, Public Improvement Districts, School Districts, and Police Jurisdictions.
     * 
     */
    DISTRICT,

    /**
     * (Military) Field Post Office.
     * 
     */
    FPO,

    /**
     * A municipality that provides local government functions.
     * 
     */
    LOCAL_IMPROVEMENT_DISTRICT,

    /**
     * An entity within a state or country, used for administrative purposes, created by territorial division for the purpose of local government (most often seen in Louisiana).
     * 
     */
    PARISH,

    /**
     * A territorial unit that acts in an administrative function or organized political system within a country. Provinces in Canada are similar to states in the United States.
     * 
     */
    PROVINCE,

    /**
     * A local jurisdiction that does not follow city or county boundaries.
     * Examples include municipal transportation authorities (MTAs), hospitals,
     * and school districts.
     * 
     */
    SPECIAL_PURPOSE_DISTRICT,

    /**
     * A territorial unit that acts in an administrative function or organized political system within a country. States in the United States are similar to provinces in Canada.
     * 
     */
    STATE,

    /**
     * A non-sovereign geographic region within a country.
     * 
     */
    TERRITORY,

    /**
     * An incorporated municipality in which definite boundaries and legal powers are set forth in a charter granted by the state, similar to a city.
     * 
     */
    TOWNSHIP,

    /**
     * A type of intergovernmental agreement where regional barriers to trade are reduced or eliminated among member countries.
     * 
     */
    TRADE_BLOCK,

    /**
     * A special-purpose district organized as either a corporation authorized
     *  by statute, or a government agency that provides public transportation
     *  within a specific region.
     * 
     */
    TRANSIT_DISTRICT;

    public String value() {
        return name();
    }

    public static JurisdictionLevelCodeType fromValue(String v) {
        return valueOf(v);
    }

}
