//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.28 at 02:15:16 PM IST 
//


package com.siteone.integration.webserviceclient.vertexclient;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:vertexinc:o-series:tps:9:0}DeductionOverride" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:vertexinc:o-series:tps:9:0}RateOverride" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:vertexinc:o-series:tps:9:0}ImpositionType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="jurisdictionLevel" use="required" type="{urn:vertexinc:o-series:tps:9:0}JurisdictionLevelCodeType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deductionOverride",
    "rateOverride",
    "impositionType"
})
@XmlRootElement(name = "JurisdictionOverride")
public class JurisdictionOverride {

    @XmlElement(name = "DeductionOverride")
    protected DeductionOverride deductionOverride;
    @XmlElement(name = "RateOverride")
    protected RateOverride rateOverride;
    @XmlElement(name = "ImpositionType")
    protected ImpositionType impositionType;
    @XmlAttribute(name = "jurisdictionLevel", required = true)
    protected JurisdictionLevelCodeType jurisdictionLevel;

    /**
     * Gets the value of the deductionOverride property.
     * 
     * @return
     *     possible object is
     *     {@link DeductionOverride }
     *     
     */
    public DeductionOverride getDeductionOverride() {
        return deductionOverride;
    }

    /**
     * Sets the value of the deductionOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeductionOverride }
     *     
     */
    public void setDeductionOverride(DeductionOverride value) {
        this.deductionOverride = value;
    }

    /**
     * Gets the value of the rateOverride property.
     * 
     * @return
     *     possible object is
     *     {@link RateOverride }
     *     
     */
    public RateOverride getRateOverride() {
        return rateOverride;
    }

    /**
     * Sets the value of the rateOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateOverride }
     *     
     */
    public void setRateOverride(RateOverride value) {
        this.rateOverride = value;
    }

    /**
     * The type description that is assigned to the imposition.
     * 
     * @return
     *     possible object is
     *     {@link ImpositionType }
     *     
     */
    public ImpositionType getImpositionType() {
        return impositionType;
    }

    /**
     * Sets the value of the impositionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImpositionType }
     *     
     */
    public void setImpositionType(ImpositionType value) {
        this.impositionType = value;
    }

    /**
     * Gets the value of the jurisdictionLevel property.
     * 
     * @return
     *     possible object is
     *     {@link JurisdictionLevelCodeType }
     *     
     */
    public JurisdictionLevelCodeType getJurisdictionLevel() {
        return jurisdictionLevel;
    }

    /**
     * Sets the value of the jurisdictionLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link JurisdictionLevelCodeType }
     *     
     */
    public void setJurisdictionLevel(JurisdictionLevelCodeType value) {
        this.jurisdictionLevel = value;
    }

}
