//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LocationType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="LocationType">
 *   <complexContent>
 *     <extension base="{urn:vertexinc:o-series:tps:9:0}PostalAddressType">
 *       <sequence>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}CurrencyConversion" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="taxAreaId" type="{urn:vertexinc:o-series:tps:9:0}TaxAreaIdType" />
 *       <attribute name="latitude">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <minLength value="1"/>
 *             <maxLength value="20"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="longitude">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <minLength value="1"/>
 *             <maxLength value="20"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="locationCustomsStatus" type="{urn:vertexinc:o-series:tps:9:0}LocationCustomsStatusCodeType" />
 *       <attribute name="locationCode" type="{urn:vertexinc:o-series:tps:9:0}LocationCodeType" />
 *       <attribute name="externalJurisdictionCode" type="{urn:vertexinc:o-series:tps:9:0}ExternalJurisdictionCodeType" />
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocationType", propOrder = {
    "currencyConversion"
})
@XmlSeeAlso({
    TaxingJurisdictionLocationType.class
})
public class LocationType
    extends PostalAddressType
{

    /**
     * The rate (multiplier) used for converting the transaction currency amount to the filing
     *                 currency amount. Pass in this value and the currency code (isoCurrencyCodeAlpha or isoCurrencyCodeNum)
     *                 to have filing currency calculated if your configuration parameters are set up to do so.
     * 
     */
    @XmlElement(name = "CurrencyConversion")
    protected CurrencyConversion currencyConversion;
    /**
     * A Vertex-specific number that identifies a tax area. If the Tax Area ID
     *                             exists in your host system, use that data to populate this data element in a request
     *                             message.
     * 
     */
    @XmlAttribute(name = "taxAreaId")
    protected Integer taxAreaId;
    /**
     * A number representing the geographical latitude coordinate of the location.
     * 
     */
    @XmlAttribute(name = "latitude")
    protected String latitude;
    /**
     * A number representing the geographical longitude coordinate of the location.
     * 
     */
    @XmlAttribute(name = "longitude")
    protected String longitude;
    /**
     * The customs status at this location. Note: this field is not applicable for InputTax TaxingJurisdictionLocation.
     * 
     */
    @XmlAttribute(name = "locationCustomsStatus")
    protected LocationCustomsStatusCodeType locationCustomsStatus;
    /**
     * A value that can be used for tax return filing in jurisdictions that require
     *                             taxes to be filed for individual retail locations.
     * 
     */
    @XmlAttribute(name = "locationCode")
    protected String locationCode;
    /**
     * The jurisdiction code assigned by the relevant governmental authority.
     * 
     */
    @XmlAttribute(name = "externalJurisdictionCode")
    protected String externalJurisdictionCode;

    /**
     * The rate (multiplier) used for converting the transaction currency amount to the filing
     *                 currency amount. Pass in this value and the currency code (isoCurrencyCodeAlpha or isoCurrencyCodeNum)
     *                 to have filing currency calculated if your configuration parameters are set up to do so.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyConversion }
     *     
     */
    public CurrencyConversion getCurrencyConversion() {
        return currencyConversion;
    }

    /**
     * Sets the value of the currencyConversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyConversion }
     *     
     * @see #getCurrencyConversion()
     */
    public void setCurrencyConversion(CurrencyConversion value) {
        this.currencyConversion = value;
    }

    /**
     * A Vertex-specific number that identifies a tax area. If the Tax Area ID
     *                             exists in your host system, use that data to populate this data element in a request
     *                             message.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTaxAreaId() {
        return taxAreaId;
    }

    /**
     * Sets the value of the taxAreaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getTaxAreaId()
     */
    public void setTaxAreaId(Integer value) {
        this.taxAreaId = value;
    }

    /**
     * A number representing the geographical latitude coordinate of the location.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getLatitude()
     */
    public void setLatitude(String value) {
        this.latitude = value;
    }

    /**
     * A number representing the geographical longitude coordinate of the location.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getLongitude()
     */
    public void setLongitude(String value) {
        this.longitude = value;
    }

    /**
     * The customs status at this location. Note: this field is not applicable for InputTax TaxingJurisdictionLocation.
     * 
     * @return
     *     possible object is
     *     {@link LocationCustomsStatusCodeType }
     *     
     */
    public LocationCustomsStatusCodeType getLocationCustomsStatus() {
        return locationCustomsStatus;
    }

    /**
     * Sets the value of the locationCustomsStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationCustomsStatusCodeType }
     *     
     * @see #getLocationCustomsStatus()
     */
    public void setLocationCustomsStatus(LocationCustomsStatusCodeType value) {
        this.locationCustomsStatus = value;
    }

    /**
     * A value that can be used for tax return filing in jurisdictions that require
     *                             taxes to be filed for individual retail locations.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationCode() {
        return locationCode;
    }

    /**
     * Sets the value of the locationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getLocationCode()
     */
    public void setLocationCode(String value) {
        this.locationCode = value;
    }

    /**
     * The jurisdiction code assigned by the relevant governmental authority.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalJurisdictionCode() {
        return externalJurisdictionCode;
    }

    /**
     * Sets the value of the externalJurisdictionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getExternalJurisdictionCode()
     */
    public void setExternalJurisdictionCode(String value) {
        this.externalJurisdictionCode = value;
    }

}
