//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Log  entry type indicates the type of log entry.
 * 
 * <p>Java class for LogEntryType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="LogEntryType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="Exception" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="logLevel" use="required" type="{urn:vertexinc:o-series:tps:9:0}LogLevelType" />
 *       <attribute name="instanceId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="threadId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="className" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LogEntryType", propOrder = {
    "message",
    "exception"
})
public class LogEntryType {

    /**
     * The exception message text.
     * 
     */
    @XmlElement(name = "Message", required = true)
    protected String message;
    /**
     * The exception name.
     * 
     */
    @XmlElement(name = "Exception")
    protected String exception;
    /**
     * The specific log level for this entry.
     * 
     */
    @XmlAttribute(name = "logLevel", required = true)
    protected LogLevelType logLevel;
    /**
     * The service instance that processed the request.
     * 
     */
    @XmlAttribute(name = "instanceId")
    protected String instanceId;
    /**
     * The thread that processed the request.
     * 
     */
    @XmlAttribute(name = "threadId")
    protected String threadId;
    /**
     * The class that generated the log entry.
     * 
     */
    @XmlAttribute(name = "className")
    protected String className;

    /**
     * The exception message text.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getMessage()
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * The exception name.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getException() {
        return exception;
    }

    /**
     * Sets the value of the exception property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getException()
     */
    public void setException(String value) {
        this.exception = value;
    }

    /**
     * The specific log level for this entry.
     * 
     * @return
     *     possible object is
     *     {@link LogLevelType }
     *     
     */
    public LogLevelType getLogLevel() {
        return logLevel;
    }

    /**
     * Sets the value of the logLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogLevelType }
     *     
     * @see #getLogLevel()
     */
    public void setLogLevel(LogLevelType value) {
        this.logLevel = value;
    }

    /**
     * The service instance that processed the request.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceId() {
        return instanceId;
    }

    /**
     * Sets the value of the instanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getInstanceId()
     */
    public void setInstanceId(String value) {
        this.instanceId = value;
    }

    /**
     * The thread that processed the request.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThreadId() {
        return threadId;
    }

    /**
     * Sets the value of the threadId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getThreadId()
     */
    public void setThreadId(String value) {
        this.threadId = value;
    }

    /**
     * The class that generated the log entry.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getClassName()
     */
    public void setClassName(String value) {
        this.className = value;
    }

}
