//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for MeasureType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="MeasureType">
 *   <simpleContent>
 *     <extension base="<http://www.w3.org/2001/XMLSchema>decimal">
 *       <attribute name="unitOfMeasure">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <minLength value="1"/>
 *             <maxLength value="3"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasureType", propOrder = {
    "value"
})
public class MeasureType {

    @XmlValue
    protected BigDecimal value;
    /**
     * The unit of measure for the line item to be used in surcharges based on
     *                             quantity and not price. For a list of the possible values, see the Supporting Information
     *                             section of the XML Integration Guide. If you pass a value that does not match the unit of
     *                             measure for the quantity-based tax rule, that rule is not used. May be Required (1) to
     *                             determine tax liability in some jurisdictions. For a line based line item in the telecommunication transaction, 
     *                             the passed in unit of measure can be converted to the tax rule unit of measure if a conversion rule exist.
     * 
     */
    @XmlAttribute(name = "unitOfMeasure")
    protected String unitOfMeasure;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    /**
     * The unit of measure for the line item to be used in surcharges based on
     *                             quantity and not price. For a list of the possible values, see the Supporting Information
     *                             section of the XML Integration Guide. If you pass a value that does not match the unit of
     *                             measure for the quantity-based tax rule, that rule is not used. May be Required (1) to
     *                             determine tax liability in some jurisdictions. For a line based line item in the telecommunication transaction, 
     *                             the passed in unit of measure can be converted to the tax rule unit of measure if a conversion rule exist.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMeasure() {
        return unitOfMeasure;
    }

    /**
     * Sets the value of the unitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getUnitOfMeasure()
     */
    public void setUnitOfMeasure(String value) {
        this.unitOfMeasure = value;
    }

}
