//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:vertexinc:o-series:tps:9:0", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.siteone.integration.webserviceclient.vertexclient;
