//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Title Transfer (or Point of Title Transfer) is the location where the title to goods
 *                 actually changes hands from seller to buyer. This location is a contractual term and is included on the
 *                 contract between buyer and seller. Title Transfer applies only to goods.
 * 
 * <p>Java class for PointOfTitleTransferCodeType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="PointOfTitleTransferCodeType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     <enumeration value="ORIGIN"/>
 *     <enumeration value="IN_TRANSIT"/>
 *     <enumeration value="DESTINATION"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "PointOfTitleTransferCodeType")
@XmlEnum
public enum PointOfTitleTransferCodeType {


    /**
     * The Title Transfer for the transaction occurred at the point of origin. The buyer
     *                         takes title at the origin and pays import tax when the goods clear customs.
     * 
     */
    ORIGIN,

    /**
     * The Title Transfer is executed in transit (for example, on the high seas). In
     *                         this scenario, no VAT is charged.
     * 
     */
    IN_TRANSIT,

    /**
     * The Title Transfer is executed at the destination. In this scenario, the supplier
     *                         is the importer of record and would be charged import VAT. Then, a domestic supply takes place
     *                         between the supplier and the buyer.
     * 
     */
    DESTINATION;

    public String value() {
        return name();
    }

    public static PointOfTitleTransferCodeType fromValue(String v) {
        return valueOf(v);
    }

}
