//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Copyright Vertex Inc. 2007-2012 All Rights Reserved
 * 
 * <p>Java class for PostalAddressType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="PostalAddressType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="StreetAddress1" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="1"/>
 *               <maxLength value="100"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="StreetAddress2" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="1"/>
 *               <maxLength value="100"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="City" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="1"/>
 *               <maxLength value="60"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="MainDivision" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="1"/>
 *               <maxLength value="60"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="SubDivision" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="1"/>
 *               <maxLength value="60"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="PostalCode" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="1"/>
 *               <maxLength value="20"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Country" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               <minLength value="1"/>
 *               <maxLength value="60"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PostalAddressType", propOrder = {
    "streetAddress1",
    "streetAddress2",
    "city",
    "mainDivision",
    "subDivision",
    "postalCode",
    "country"
})
@XmlSeeAlso({
    com.siteone.integration.webserviceclient.vertexclient.TaxRegistrationType.PhysicalLocation.class,
    LocationType.class
})
public class PostalAddressType {

    /**
     * The first line of the street address.
     * 
     */
    @XmlElement(name = "StreetAddress1")
    protected String streetAddress1;
    /**
     * The second address line for a Contact.
     * 
     */
    @XmlElement(name = "StreetAddress2")
    protected String streetAddress2;
    /**
     * The proper name of the city used to determine the Tax Area ID (if none is supplied). Optional (0..1) but recommended for greatest accuracy if no Tax Area ID is supplied.
     * 
     */
    @XmlElement(name = "City")
    protected String city;
    /**
     * The proper name or the postal abbreviation of the state, province, or territory used to determine the Tax Area ID if none is supplied. Optional (0..1) but is recommended for greatest accuracy if no Tax Area ID is supplied.
     * 
     */
    @XmlElement(name = "MainDivision")
    protected String mainDivision;
    /**
     * The name of the county used to determine the Tax Area ID if none is supplied. Optional (0..1) but is recommended for greatest accuracy if no Tax Area ID is supplied.
     * 
     */
    @XmlElement(name = "SubDivision")
    protected String subDivision;
    /**
     * The postal code used to determine the Tax Area ID (if none is supplied). For valid formats, see the Supporting Information section in the XML Integration Guide. Optional (0..1) but recommended for greatest accuracy if no Tax Area ID is supplied.
     * 
     */
    @XmlElement(name = "PostalCode")
    protected String postalCode;
    /**
     * The country used to determine the Tax Area ID (if none is supplied). You can use a Data Extract report to see the valid country values. (Refer to the Vertex Central online help for information on running Data Extract reports.) Defaults to the value of the taxgis.jurisdictionfinder.DefaultCountryCodeForAddress parameter. The default value for this parameter is USA. (For details on this configuration parameter, refer to the Configuration File Parameters Reference Guide.)
     * 
     */
    @XmlElement(name = "Country")
    protected String country;

    /**
     * The first line of the street address.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetAddress1() {
        return streetAddress1;
    }

    /**
     * Sets the value of the streetAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getStreetAddress1()
     */
    public void setStreetAddress1(String value) {
        this.streetAddress1 = value;
    }

    /**
     * The second address line for a Contact.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetAddress2() {
        return streetAddress2;
    }

    /**
     * Sets the value of the streetAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getStreetAddress2()
     */
    public void setStreetAddress2(String value) {
        this.streetAddress2 = value;
    }

    /**
     * The proper name of the city used to determine the Tax Area ID (if none is supplied). Optional (0..1) but recommended for greatest accuracy if no Tax Area ID is supplied.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCity()
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * The proper name or the postal abbreviation of the state, province, or territory used to determine the Tax Area ID if none is supplied. Optional (0..1) but is recommended for greatest accuracy if no Tax Area ID is supplied.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainDivision() {
        return mainDivision;
    }

    /**
     * Sets the value of the mainDivision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getMainDivision()
     */
    public void setMainDivision(String value) {
        this.mainDivision = value;
    }

    /**
     * The name of the county used to determine the Tax Area ID if none is supplied. Optional (0..1) but is recommended for greatest accuracy if no Tax Area ID is supplied.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubDivision() {
        return subDivision;
    }

    /**
     * Sets the value of the subDivision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSubDivision()
     */
    public void setSubDivision(String value) {
        this.subDivision = value;
    }

    /**
     * The postal code used to determine the Tax Area ID (if none is supplied). For valid formats, see the Supporting Information section in the XML Integration Guide. Optional (0..1) but recommended for greatest accuracy if no Tax Area ID is supplied.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getPostalCode()
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * The country used to determine the Tax Area ID (if none is supplied). You can use a Data Extract report to see the valid country values. (Refer to the Vertex Central online help for information on running Data Extract reports.) Defaults to the value of the taxgis.jurisdictionfinder.DefaultCountryCodeForAddress parameter. The default value for this parameter is USA. (For details on this configuration parameter, refer to the Configuration File Parameters Reference Guide.)
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getCountry()
     */
    public void setCountry(String value) {
        this.country = value;
    }

}
