//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <simpleContent>
 *     <extension base="<urn:vertexinc:o-series:tps:9:0>EntityCodeType">
 *       <attribute name="productClass" type="{urn:vertexinc:o-series:tps:9:0}EntityCodeType" />
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "Product")
public class Product {

    @XmlValue
    protected String value;
    /**
     * A code used to represent groups or categories of products or services
     *                                 with similar taxability. You can use the Vertex Central user interface to map your
     *                                 products classes to Product Class Categories. If the supplied Product and Product Class
     *                                 information is not recognized by the calculation engine, a general category indicating
     *                                 TPP is assigned. Required (1) if no Product information is supplied. If both are
     *                                 supplied, Product information supersedes Product Class information.
     * 
     */
    @XmlAttribute(name = "productClass")
    protected String productClass;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * A code used to represent groups or categories of products or services
     *                                 with similar taxability. You can use the Vertex Central user interface to map your
     *                                 products classes to Product Class Categories. If the supplied Product and Product Class
     *                                 information is not recognized by the calculation engine, a general category indicating
     *                                 TPP is assigned. Required (1) if no Product information is supplied. If both are
     *                                 supplied, Product information supersedes Product Class information.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductClass() {
        return productClass;
    }

    /**
     * Sets the value of the productClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getProductClass()
     */
    public void setProductClass(String value) {
        this.productClass = value;
    }

}
