//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <simpleContent>
 *     <extension base="<urn:vertexinc:o-series:tps:9:0>EntityCodeType">
 *       <attribute name="purchaseClass" type="{urn:vertexinc:o-series:tps:9:0}EntityCodeType" />
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "Purchase")
public class Purchase {

    @XmlValue
    protected String value;
    /**
     * A code from the host application that identifies a general classification
     *                                 of product, material, service or SKU code.
     * 
     */
    @XmlAttribute(name = "purchaseClass")
    protected String purchaseClass;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * A code from the host application that identifies a general classification
     *                                 of product, material, service or SKU code.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaseClass() {
        return purchaseClass;
    }

    /**
     * Sets the value of the purchaseClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getPurchaseClass()
     */
    public void setPurchaseClass(String value) {
        this.purchaseClass = value;
    }

}
