//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Quotation Response message.
 * 
 * <p>Java class for QuotationResponseType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="QuotationResponseType">
 *   <complexContent>
 *     <extension base="{urn:vertexinc:o-series:tps:9:0}TaxTransactionResponseType">
 *       <sequence>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}Currency" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}OriginalCurrency" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}CompanyCodeCurrency" minOccurs="0"/>
 *         <element name="Seller" type="{urn:vertexinc:o-series:tps:9:0}SellerType" minOccurs="0"/>
 *         <element name="Customer" type="{urn:vertexinc:o-series:tps:9:0}CustomerType" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}TaxOverride" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}ImpositionToProcess" maxOccurs="unbounded" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}JurisdictionOverride" maxOccurs="unbounded" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}SitusOverride" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}Discount" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}ProratePercentage" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}SubTotal" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}Total" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}TotalTax" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}CurrencyConversionFactors" minOccurs="0"/>
 *         <element name="LineItem" type="{urn:vertexinc:o-series:tps:9:0}LineItemQSOType" maxOccurs="unbounded"/>
 *       </sequence>
 *       <attGroup ref="{urn:vertexinc:o-series:tps:9:0}QuotationTransactionGroup"/>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuotationResponseType", propOrder = {
    "currency",
    "originalCurrency",
    "companyCodeCurrency",
    "seller",
    "customer",
    "taxOverride",
    "impositionToProcess",
    "jurisdictionOverride",
    "situsOverride",
    "discount",
    "proratePercentage",
    "subTotal",
    "total",
    "totalTax",
    "currencyConversionFactors",
    "lineItem"
})
public class QuotationResponseType
    extends TaxTransactionResponseType
{

    /**
     * Default unit of currency for the entire transaction.
     * 
     */
    @XmlElement(name = "Currency")
    protected CurrencyType currency;
    /**
     * This represents the currency in which the original business transaction took place.
     * 
     */
    @XmlElement(name = "OriginalCurrency")
    protected CurrencyType originalCurrency;
    /**
     * The default currency code of the company that is integrated with the ERP or host system.
     *                 O Series does not use this field in tax calculations.
     * 
     */
    @XmlElement(name = "CompanyCodeCurrency")
    protected CurrencyType companyCodeCurrency;
    /**
     * The seller  for the transaction.
     * 
     */
    @XmlElement(name = "Seller")
    protected SellerType seller;
    /**
     * The customer for the transaction.
     * 
     */
    @XmlElement(name = "Customer")
    protected CustomerType customer;
    /**
     * Details on the tax override.
     * 
     */
    @XmlElement(name = "TaxOverride")
    protected TaxOverride taxOverride;
    /**
     * Limits the taxes calculated for the transaction to a specific jurisdiction level and
     *                 imposition type.
     * 
     */
    @XmlElement(name = "ImpositionToProcess")
    protected List<ImpositionToProcess> impositionToProcess;
    /**
     * Details on the jurisdiction overrides.
     * 
     */
    @XmlElement(name = "JurisdictionOverride")
    protected List<JurisdictionOverride> jurisdictionOverride;
    /**
     * Details on the situs determination overrides.
     * 
     */
    @XmlElement(name = "SitusOverride")
    protected SitusOverride situsOverride;
    /**
     * Details on the discount. To pass Discount information, pass either DiscountPercent or
     *                 DiscountAmount, but not both.
     * 
     */
    @XmlElement(name = "Discount")
    protected Discount discount;
    /**
     * Percentage passed from the billing system to calculate a remainder of an assessed tax or fee.
     * 
     */
    @XmlElement(name = "ProratePercentage")
    protected BigDecimal proratePercentage;
    /**
     * Sum of all extended amounts for line items in the transaction.
     * 
     */
    @XmlElement(name = "SubTotal")
    protected BigDecimal subTotal;
    /**
     * Total tax amount of each line item.
     * 
     */
    @XmlElement(name = "Total")
    protected BigDecimal total;
    /**
     * Amount of tax based on variables of transaction.
     * 
     */
    @XmlElement(name = "TotalTax")
    protected BigDecimal totalTax;
    /**
     * A list of conversion factors that Vertex O Series requires to perform currency conversion. These factors include Source Currency, Target Currency, and Conversion Factor.
     * 
     */
    @XmlElement(name = "CurrencyConversionFactors")
    protected CurrencyConversionFactors currencyConversionFactors;
    /**
     * The header for a component of a transaction.  A line item is required for each component of the transaction. Each transaction requires at least one line item. Note that a line item can contain child line items.
     * 
     */
    @XmlElement(name = "LineItem", required = true)
    protected List<LineItemQSOType> lineItem;
    /**
     * The document number in the host application that references the event.
     * 
     */
    @XmlAttribute(name = "documentNumber")
    protected String documentNumber;
    /**
     * A string to represent the accumulation invoice identity.
     * 
     */
    @XmlAttribute(name = "accumulationDocumentNumber")
    protected String accumulationDocumentNumber;
    /**
     * A string to represent the accumulation customer identity.
     * 
     */
    @XmlAttribute(name = "accumulationCustomerNumber")
    protected String accumulationCustomerNumber;
    /**
     * Indicates the type of business transaction to be posted. This field is on the transaction level.
     * 
     */
    @XmlAttribute(name = "documentType")
    protected String documentType;
    /**
     * Indicates the billing documents that specify different business transactions that are involved in billing activities. Examples of billing documents include  invoice, credit or debit memo, or cancellation document. This field is on the transaction level.
     * 
     */
    @XmlAttribute(name = "billingType")
    protected String billingType;
    /**
     * The key that identifies the purpose of the order. This field is on the transaction level.
     * 
     */
    @XmlAttribute(name = "orderType")
    protected String orderType;
    /**
     * The date when the transaction is posted for auditing and reporting purposes. If no date is provided, the Calculation Engine uses the date when the transaction was processed.
     * 
     */
    @XmlAttribute(name = "postingDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar postingDate;
    /**
     * A value that can be used for tax return filing in jurisdictions that require taxes to be filed for individual retail locations.
     * 
     */
    @XmlAttribute(name = "locationCode")
    protected String locationCode;
    /**
     * Indicates whether the response message should contain an additional structure that shows the elements/attributes that were changed by Tax Assist. This is for informational purposes only and contains no tax results.
     * 
     */
    @XmlAttribute(name = "returnAssistedParametersIndicator")
    protected Boolean returnAssistedParametersIndicator;
    /**
     * If this indicator is set, the response message returns child line items that were generated by the Tax Assist allocation feature. Otherwise, these line items are deleted after the transaction is written to the Tax Journal and only the primary line item, which contains the combined tax results of the child line items, is passed back to the host system.
     * 
     */
    @XmlAttribute(name = "returnGeneratedLineItemsIndicator")
    protected Boolean returnGeneratedLineItemsIndicator;
    /**
     * An identifier that determines the vendor or customer jurisdiction in which the title transfer of a supply takes place. This is also known as Shipping Terms. Delivery Terms information could be critical to determine the place of supply, for example, in distance selling.
     * 
     */
    @XmlAttribute(name = "deliveryTerm")
    protected DeliveryTermCodeType deliveryTerm;
    /**
     * The actual date of the requested action. The calculation engine uses this date to determine the valid tax rates and rules.
     * 
     */
    @XmlAttribute(name = "documentDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar documentDate;
    /**
     * An identifier that further defines the document and corresponds to the transaction stored in the host system. The Transaction ID is used for synchronization services, but is not used for reporting purposes.
     * 
     */
    @XmlAttribute(name = "transactionId")
    protected String transactionId;
    /**
     * An identifier for the specific transaction type to be used by the transaction and/or line item. If transactionType is not set at the line item level, the line item uses the transaction level value.
     * 
     */
    @XmlAttribute(name = "transactionType", required = true)
    protected SaleTransactionType transactionType;
    /**
     * A code that indicates a special action on the transaction being processed.
     * 
     */
    @XmlAttribute(name = "simplificationCode")
    protected SimplificationCodeType simplificationCode;
    /**
     * The roundAtLineLevel attribute enables you to apply line-item level or invoice-level rounding to tax calculations. Set this attribute to True to set up line-item level rounding. With line-item level rounding, the Calculation Engine rounds amounts at the line-item level and then sums those amounts to calculate an invoice total. This method is useful for invoices that include line items with different taxing jurisdictions.
     * 
     * The default value for this attribute is False. In this case, O Series applies an invoice-level rounding, where the Calculation Engine compares the sum of rounded line item-level totals to the rounded invoice-level total. When there is a difference between these totals, the Calculation Engine compares differences between rounded and unrounded amounts at each jurisdiction level and distributes the difference to the jurisdiction that results in the smallest total rounding difference amount. For more information about invoice-level rounding, contact Vertex Product Support to obtain the Rounding Guide.
     * 
     */
    @XmlAttribute(name = "roundAtLineLevel")
    protected Boolean roundAtLineLevel;
    /**
     * The date the purchaser paid for the product. If the purchaser pays for the product but physically receives it at a later date, Vertex O Series uses this field for returns and reporting for your tax type.  This field is also used in cash accounting.
     * 
     */
    @XmlAttribute(name = "paymentDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar paymentDate;
    /**
     * Supports reporting and the document sequence identifier used by your ERP system. Some countries require that documents follow a unique sequential sequence number, depending on the registration type and the type of invoice. Use this field for audit purposes to track the sequence of your documents. This field is used in European Union (EU) countries.
     * 
     */
    @XmlAttribute(name = "documentSequenceId")
    protected String documentSequenceId;
    /**
     * The date that drives the timing of when the VAT liability arises. In some countries, if the Tax Point Date, (also called the Time of Supply) is different from the invoice date, this field is shown separately on an invoice. Use this field if you have reporting compliance in Spain, Poland, and Hungary.
     * 
     */
    @XmlAttribute(name = "taxPointDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar taxPointDate;

    /**
     * Default unit of currency for the entire transaction.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyType }
     *     
     */
    public CurrencyType getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyType }
     *     
     * @see #getCurrency()
     */
    public void setCurrency(CurrencyType value) {
        this.currency = value;
    }

    /**
     * This represents the currency in which the original business transaction took place.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyType }
     *     
     */
    public CurrencyType getOriginalCurrency() {
        return originalCurrency;
    }

    /**
     * Sets the value of the originalCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyType }
     *     
     * @see #getOriginalCurrency()
     */
    public void setOriginalCurrency(CurrencyType value) {
        this.originalCurrency = value;
    }

    /**
     * The default currency code of the company that is integrated with the ERP or host system.
     *                 O Series does not use this field in tax calculations.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyType }
     *     
     */
    public CurrencyType getCompanyCodeCurrency() {
        return companyCodeCurrency;
    }

    /**
     * Sets the value of the companyCodeCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyType }
     *     
     * @see #getCompanyCodeCurrency()
     */
    public void setCompanyCodeCurrency(CurrencyType value) {
        this.companyCodeCurrency = value;
    }

    /**
     * The seller  for the transaction.
     * 
     * @return
     *     possible object is
     *     {@link SellerType }
     *     
     */
    public SellerType getSeller() {
        return seller;
    }

    /**
     * Sets the value of the seller property.
     * 
     * @param value
     *     allowed object is
     *     {@link SellerType }
     *     
     * @see #getSeller()
     */
    public void setSeller(SellerType value) {
        this.seller = value;
    }

    /**
     * The customer for the transaction.
     * 
     * @return
     *     possible object is
     *     {@link CustomerType }
     *     
     */
    public CustomerType getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerType }
     *     
     * @see #getCustomer()
     */
    public void setCustomer(CustomerType value) {
        this.customer = value;
    }

    /**
     * Details on the tax override.
     * 
     * @return
     *     possible object is
     *     {@link TaxOverride }
     *     
     */
    public TaxOverride getTaxOverride() {
        return taxOverride;
    }

    /**
     * Sets the value of the taxOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxOverride }
     *     
     * @see #getTaxOverride()
     */
    public void setTaxOverride(TaxOverride value) {
        this.taxOverride = value;
    }

    /**
     * Limits the taxes calculated for the transaction to a specific jurisdiction level and
     *                 imposition type.
     * 
     * Gets the value of the impositionToProcess property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the impositionToProcess property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getImpositionToProcess().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImpositionToProcess }
     * </p>
     * 
     * 
     * @return
     *     The value of the impositionToProcess property.
     */
    public List<ImpositionToProcess> getImpositionToProcess() {
        if (impositionToProcess == null) {
            impositionToProcess = new ArrayList<>();
        }
        return this.impositionToProcess;
    }

    /**
     * Details on the jurisdiction overrides.
     * 
     * Gets the value of the jurisdictionOverride property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jurisdictionOverride property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getJurisdictionOverride().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JurisdictionOverride }
     * </p>
     * 
     * 
     * @return
     *     The value of the jurisdictionOverride property.
     */
    public List<JurisdictionOverride> getJurisdictionOverride() {
        if (jurisdictionOverride == null) {
            jurisdictionOverride = new ArrayList<>();
        }
        return this.jurisdictionOverride;
    }

    /**
     * Details on the situs determination overrides.
     * 
     * @return
     *     possible object is
     *     {@link SitusOverride }
     *     
     */
    public SitusOverride getSitusOverride() {
        return situsOverride;
    }

    /**
     * Sets the value of the situsOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link SitusOverride }
     *     
     * @see #getSitusOverride()
     */
    public void setSitusOverride(SitusOverride value) {
        this.situsOverride = value;
    }

    /**
     * Details on the discount. To pass Discount information, pass either DiscountPercent or
     *                 DiscountAmount, but not both.
     * 
     * @return
     *     possible object is
     *     {@link Discount }
     *     
     */
    public Discount getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Discount }
     *     
     * @see #getDiscount()
     */
    public void setDiscount(Discount value) {
        this.discount = value;
    }

    /**
     * Percentage passed from the billing system to calculate a remainder of an assessed tax or fee.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProratePercentage() {
        return proratePercentage;
    }

    /**
     * Sets the value of the proratePercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getProratePercentage()
     */
    public void setProratePercentage(BigDecimal value) {
        this.proratePercentage = value;
    }

    /**
     * Sum of all extended amounts for line items in the transaction.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSubTotal() {
        return subTotal;
    }

    /**
     * Sets the value of the subTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getSubTotal()
     */
    public void setSubTotal(BigDecimal value) {
        this.subTotal = value;
    }

    /**
     * Total tax amount of each line item.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getTotal()
     */
    public void setTotal(BigDecimal value) {
        this.total = value;
    }

    /**
     * Amount of tax based on variables of transaction.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalTax() {
        return totalTax;
    }

    /**
     * Sets the value of the totalTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getTotalTax()
     */
    public void setTotalTax(BigDecimal value) {
        this.totalTax = value;
    }

    /**
     * A list of conversion factors that Vertex O Series requires to perform currency conversion. These factors include Source Currency, Target Currency, and Conversion Factor.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyConversionFactors }
     *     
     */
    public CurrencyConversionFactors getCurrencyConversionFactors() {
        return currencyConversionFactors;
    }

    /**
     * Sets the value of the currencyConversionFactors property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyConversionFactors }
     *     
     * @see #getCurrencyConversionFactors()
     */
    public void setCurrencyConversionFactors(CurrencyConversionFactors value) {
        this.currencyConversionFactors = value;
    }

    /**
     * The header for a component of a transaction.  A line item is required for each component of the transaction. Each transaction requires at least one line item. Note that a line item can contain child line items.
     * 
     * Gets the value of the lineItem property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineItem property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getLineItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LineItemQSOType }
     * </p>
     * 
     * 
     * @return
     *     The value of the lineItem property.
     */
    public List<LineItemQSOType> getLineItem() {
        if (lineItem == null) {
            lineItem = new ArrayList<>();
        }
        return this.lineItem;
    }

    /**
     * The document number in the host application that references the event.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentNumber() {
        return documentNumber;
    }

    /**
     * Sets the value of the documentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDocumentNumber()
     */
    public void setDocumentNumber(String value) {
        this.documentNumber = value;
    }

    /**
     * A string to represent the accumulation invoice identity.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccumulationDocumentNumber() {
        return accumulationDocumentNumber;
    }

    /**
     * Sets the value of the accumulationDocumentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getAccumulationDocumentNumber()
     */
    public void setAccumulationDocumentNumber(String value) {
        this.accumulationDocumentNumber = value;
    }

    /**
     * A string to represent the accumulation customer identity.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccumulationCustomerNumber() {
        return accumulationCustomerNumber;
    }

    /**
     * Sets the value of the accumulationCustomerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getAccumulationCustomerNumber()
     */
    public void setAccumulationCustomerNumber(String value) {
        this.accumulationCustomerNumber = value;
    }

    /**
     * Indicates the type of business transaction to be posted. This field is on the transaction level.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDocumentType()
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Indicates the billing documents that specify different business transactions that are involved in billing activities. Examples of billing documents include  invoice, credit or debit memo, or cancellation document. This field is on the transaction level.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingType() {
        return billingType;
    }

    /**
     * Sets the value of the billingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getBillingType()
     */
    public void setBillingType(String value) {
        this.billingType = value;
    }

    /**
     * The key that identifies the purpose of the order. This field is on the transaction level.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getOrderType()
     */
    public void setOrderType(String value) {
        this.orderType = value;
    }

    /**
     * The date when the transaction is posted for auditing and reporting purposes. If no date is provided, the Calculation Engine uses the date when the transaction was processed.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPostingDate() {
        return postingDate;
    }

    /**
     * Sets the value of the postingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getPostingDate()
     */
    public void setPostingDate(XMLGregorianCalendar value) {
        this.postingDate = value;
    }

    /**
     * A value that can be used for tax return filing in jurisdictions that require taxes to be filed for individual retail locations.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationCode() {
        return locationCode;
    }

    /**
     * Sets the value of the locationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getLocationCode()
     */
    public void setLocationCode(String value) {
        this.locationCode = value;
    }

    /**
     * Indicates whether the response message should contain an additional structure that shows the elements/attributes that were changed by Tax Assist. This is for informational purposes only and contains no tax results.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReturnAssistedParametersIndicator() {
        return returnAssistedParametersIndicator;
    }

    /**
     * Sets the value of the returnAssistedParametersIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #isReturnAssistedParametersIndicator()
     */
    public void setReturnAssistedParametersIndicator(Boolean value) {
        this.returnAssistedParametersIndicator = value;
    }

    /**
     * If this indicator is set, the response message returns child line items that were generated by the Tax Assist allocation feature. Otherwise, these line items are deleted after the transaction is written to the Tax Journal and only the primary line item, which contains the combined tax results of the child line items, is passed back to the host system.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReturnGeneratedLineItemsIndicator() {
        return returnGeneratedLineItemsIndicator;
    }

    /**
     * Sets the value of the returnGeneratedLineItemsIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #isReturnGeneratedLineItemsIndicator()
     */
    public void setReturnGeneratedLineItemsIndicator(Boolean value) {
        this.returnGeneratedLineItemsIndicator = value;
    }

    /**
     * An identifier that determines the vendor or customer jurisdiction in which the title transfer of a supply takes place. This is also known as Shipping Terms. Delivery Terms information could be critical to determine the place of supply, for example, in distance selling.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryTermCodeType }
     *     
     */
    public DeliveryTermCodeType getDeliveryTerm() {
        return deliveryTerm;
    }

    /**
     * Sets the value of the deliveryTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryTermCodeType }
     *     
     * @see #getDeliveryTerm()
     */
    public void setDeliveryTerm(DeliveryTermCodeType value) {
        this.deliveryTerm = value;
    }

    /**
     * The actual date of the requested action. The calculation engine uses this date to determine the valid tax rates and rules.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDocumentDate() {
        return documentDate;
    }

    /**
     * Sets the value of the documentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getDocumentDate()
     */
    public void setDocumentDate(XMLGregorianCalendar value) {
        this.documentDate = value;
    }

    /**
     * An identifier that further defines the document and corresponds to the transaction stored in the host system. The Transaction ID is used for synchronization services, but is not used for reporting purposes.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getTransactionId()
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * An identifier for the specific transaction type to be used by the transaction and/or line item. If transactionType is not set at the line item level, the line item uses the transaction level value.
     * 
     * @return
     *     possible object is
     *     {@link SaleTransactionType }
     *     
     */
    public SaleTransactionType getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SaleTransactionType }
     *     
     * @see #getTransactionType()
     */
    public void setTransactionType(SaleTransactionType value) {
        this.transactionType = value;
    }

    /**
     * A code that indicates a special action on the transaction being processed.
     * 
     * @return
     *     possible object is
     *     {@link SimplificationCodeType }
     *     
     */
    public SimplificationCodeType getSimplificationCode() {
        return simplificationCode;
    }

    /**
     * Sets the value of the simplificationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimplificationCodeType }
     *     
     * @see #getSimplificationCode()
     */
    public void setSimplificationCode(SimplificationCodeType value) {
        this.simplificationCode = value;
    }

    /**
     * The roundAtLineLevel attribute enables you to apply line-item level or invoice-level rounding to tax calculations. Set this attribute to True to set up line-item level rounding. With line-item level rounding, the Calculation Engine rounds amounts at the line-item level and then sums those amounts to calculate an invoice total. This method is useful for invoices that include line items with different taxing jurisdictions.
     * 
     * The default value for this attribute is False. In this case, O Series applies an invoice-level rounding, where the Calculation Engine compares the sum of rounded line item-level totals to the rounded invoice-level total. When there is a difference between these totals, the Calculation Engine compares differences between rounded and unrounded amounts at each jurisdiction level and distributes the difference to the jurisdiction that results in the smallest total rounding difference amount. For more information about invoice-level rounding, contact Vertex Product Support to obtain the Rounding Guide.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRoundAtLineLevel() {
        return roundAtLineLevel;
    }

    /**
     * Sets the value of the roundAtLineLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #isRoundAtLineLevel()
     */
    public void setRoundAtLineLevel(Boolean value) {
        this.roundAtLineLevel = value;
    }

    /**
     * The date the purchaser paid for the product. If the purchaser pays for the product but physically receives it at a later date, Vertex O Series uses this field for returns and reporting for your tax type.  This field is also used in cash accounting.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPaymentDate() {
        return paymentDate;
    }

    /**
     * Sets the value of the paymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getPaymentDate()
     */
    public void setPaymentDate(XMLGregorianCalendar value) {
        this.paymentDate = value;
    }

    /**
     * Supports reporting and the document sequence identifier used by your ERP system. Some countries require that documents follow a unique sequential sequence number, depending on the registration type and the type of invoice. Use this field for audit purposes to track the sequence of your documents. This field is used in European Union (EU) countries.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentSequenceId() {
        return documentSequenceId;
    }

    /**
     * Sets the value of the documentSequenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDocumentSequenceId()
     */
    public void setDocumentSequenceId(String value) {
        this.documentSequenceId = value;
    }

    /**
     * The date that drives the timing of when the VAT liability arises. In some countries, if the Tax Point Date, (also called the Time of Supply) is different from the invoice date, this field is shown separately on an invoice. Use this field if you have reporting compliance in Spain, Poland, and Hungary.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTaxPointDate() {
        return taxPointDate;
    }

    /**
     * Sets the value of the taxPointDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getTaxPointDate()
     */
    public void setTaxPointDate(XMLGregorianCalendar value) {
        this.taxPointDate = value;
    }

}
