//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="ReturnsCodeField" maxOccurs="unbounded" minOccurs="0">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.w3.org/2001/XMLSchema>string">
 *                 <attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="ReturnsNumericField" maxOccurs="unbounded" minOccurs="0">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.w3.org/2001/XMLSchema>decimal">
 *                 <attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="ReturnsDateField" maxOccurs="unbounded" minOccurs="0">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.w3.org/2001/XMLSchema>date">
 *                 <attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="ReturnsIndicatorField" maxOccurs="unbounded" minOccurs="0">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.w3.org/2001/XMLSchema>boolean">
 *                 <attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "returnsCodeField",
    "returnsNumericField",
    "returnsDateField",
    "returnsIndicatorField"
})
@XmlRootElement(name = "ReturnsFields")
public class ReturnsFields {

    /**
     * A text value for your returns. If you require a
     *                             country-specific setting, preface this text with the ISO 3166-1 alpha-2
     *                             country code and an underscore.
     * 
     *                             This field is included on the Returns report that is associated with your tax type. For
     *                             example, this field is included in VAT Returns reports. This field is not available for U.S.
     *                             transactions.
     * 
     */
    @XmlElement(name = "ReturnsCodeField")
    protected List<ReturnsFields.ReturnsCodeField> returnsCodeField;
    /**
     * A numeric value for your returns. If you require a
     *                             country-specific setting, preface this number with the ISO 3166-1 alpha-2 country code and
     *                             an underscore.
     * 
     *                             This field is included on the Returns report that is associated with your tax type. For
     *                             example, this field is included in VAT Returns reports. This field is not available for U.S.
     *                             transactions.
     * 
     */
    @XmlElement(name = "ReturnsNumericField")
    protected List<ReturnsFields.ReturnsNumericField> returnsNumericField;
    /**
     * A date value for your returns. If you require a
     *                             country-specific setting, preface this date with the ISO 3166-1 alpha-2
     *                             country code and an underscore.
     * 
     *                             This field is included on the Returns report that is associated with your tax type. For
     *                             example, this field is included in VAT Returns reports. This field is not available for U.S.
     *                             transactions.
     * 
     */
    @XmlElement(name = "ReturnsDateField")
    protected List<ReturnsFields.ReturnsDateField> returnsDateField;
    /**
     * A Boolean value for your returns. If you require a
     *                             country-specific setting, preface this value with the ISO 3166-1 alpha-2 country code and an
     *                             underscore.
     * 
     *                             This field is included on the Returns report that is associated with your tax type. For
     *                             example, this field is included in VAT Returns reports. This field is not available for US
     *                             transactions.
     * 
     */
    @XmlElement(name = "ReturnsIndicatorField")
    protected List<ReturnsFields.ReturnsIndicatorField> returnsIndicatorField;

    /**
     * A text value for your returns. If you require a
     *                             country-specific setting, preface this text with the ISO 3166-1 alpha-2
     *                             country code and an underscore.
     * 
     *                             This field is included on the Returns report that is associated with your tax type. For
     *                             example, this field is included in VAT Returns reports. This field is not available for U.S.
     *                             transactions.
     * 
     * Gets the value of the returnsCodeField property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the returnsCodeField property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getReturnsCodeField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReturnsFields.ReturnsCodeField }
     * </p>
     * 
     * 
     * @return
     *     The value of the returnsCodeField property.
     */
    public List<ReturnsFields.ReturnsCodeField> getReturnsCodeField() {
        if (returnsCodeField == null) {
            returnsCodeField = new ArrayList<>();
        }
        return this.returnsCodeField;
    }

    /**
     * A numeric value for your returns. If you require a
     *                             country-specific setting, preface this number with the ISO 3166-1 alpha-2 country code and
     *                             an underscore.
     * 
     *                             This field is included on the Returns report that is associated with your tax type. For
     *                             example, this field is included in VAT Returns reports. This field is not available for U.S.
     *                             transactions.
     * 
     * Gets the value of the returnsNumericField property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the returnsNumericField property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getReturnsNumericField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReturnsFields.ReturnsNumericField }
     * </p>
     * 
     * 
     * @return
     *     The value of the returnsNumericField property.
     */
    public List<ReturnsFields.ReturnsNumericField> getReturnsNumericField() {
        if (returnsNumericField == null) {
            returnsNumericField = new ArrayList<>();
        }
        return this.returnsNumericField;
    }

    /**
     * A date value for your returns. If you require a
     *                             country-specific setting, preface this date with the ISO 3166-1 alpha-2
     *                             country code and an underscore.
     * 
     *                             This field is included on the Returns report that is associated with your tax type. For
     *                             example, this field is included in VAT Returns reports. This field is not available for U.S.
     *                             transactions.
     * 
     * Gets the value of the returnsDateField property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the returnsDateField property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getReturnsDateField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReturnsFields.ReturnsDateField }
     * </p>
     * 
     * 
     * @return
     *     The value of the returnsDateField property.
     */
    public List<ReturnsFields.ReturnsDateField> getReturnsDateField() {
        if (returnsDateField == null) {
            returnsDateField = new ArrayList<>();
        }
        return this.returnsDateField;
    }

    /**
     * A Boolean value for your returns. If you require a
     *                             country-specific setting, preface this value with the ISO 3166-1 alpha-2 country code and an
     *                             underscore.
     * 
     *                             This field is included on the Returns report that is associated with your tax type. For
     *                             example, this field is included in VAT Returns reports. This field is not available for US
     *                             transactions.
     * 
     * Gets the value of the returnsIndicatorField property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the returnsIndicatorField property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getReturnsIndicatorField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReturnsFields.ReturnsIndicatorField }
     * </p>
     * 
     * 
     * @return
     *     The value of the returnsIndicatorField property.
     */
    public List<ReturnsFields.ReturnsIndicatorField> getReturnsIndicatorField() {
        if (returnsIndicatorField == null) {
            returnsIndicatorField = new ArrayList<>();
        }
        return this.returnsIndicatorField;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.w3.org/2001/XMLSchema>string">
     *       <attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ReturnsCodeField {

        @XmlValue
        protected String value;
        /**
         * The name of the Returns Code field.
         * 
         */
        @XmlAttribute(name = "name", required = true)
        protected String name;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * The name of the Returns Code field.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getName()
         */
        public void setName(String value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.w3.org/2001/XMLSchema>date">
     *       <attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ReturnsDateField {

        @XmlValue
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar value;
        /**
         * The name of the Returns Date field.
         * 
         */
        @XmlAttribute(name = "name", required = true)
        protected String name;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setValue(XMLGregorianCalendar value) {
            this.value = value;
        }

        /**
         * The name of the Returns Date field.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getName()
         */
        public void setName(String value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.w3.org/2001/XMLSchema>boolean">
     *       <attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ReturnsIndicatorField {

        @XmlValue
        protected boolean value;
        /**
         * The name of the Returns Indicator field.
         * 
         */
        @XmlAttribute(name = "name", required = true)
        protected String name;

        /**
         * Gets the value of the value property.
         * 
         */
        public boolean isValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(boolean value) {
            this.value = value;
        }

        /**
         * The name of the Returns Indicator field.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getName()
         */
        public void setName(String value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.w3.org/2001/XMLSchema>decimal">
     *       <attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ReturnsNumericField {

        @XmlValue
        protected BigDecimal value;
        /**
         * The name of the Returns Numeric field.
         * 
         */
        @XmlAttribute(name = "name", required = true)
        protected String name;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setValue(BigDecimal value) {
            this.value = value;
        }

        /**
         * The name of the Returns Numeric field.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getName()
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
