//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for TaxAreaResultType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="TaxAreaResultType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Jurisdiction" type="{urn:vertexinc:o-series:tps:9:0}JurisdictionType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}PostalAddress" maxOccurs="unbounded" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}Coordinates" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="Status" maxOccurs="unbounded" minOccurs="0">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.w3.org/2001/XMLSchema>string">
 *                 <attribute name="lookupResult" use="required" type="{urn:vertexinc:o-series:tps:9:0}LookupResultType" />
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="AddressCleansingResultMessage" maxOccurs="unbounded" minOccurs="0">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.w3.org/2001/XMLSchema>string">
 *                 <attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 <attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *       <attribute name="taxAreaId" type="{urn:vertexinc:o-series:tps:9:0}TaxAreaIdType" />
 *       <attribute name="asOfDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       <attribute name="confidenceIndicator">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             <minInclusive value="0"/>
 *             <maxInclusive value="100"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxAreaResultType", propOrder = {
    "jurisdiction",
    "postalAddress",
    "coordinates",
    "status",
    "addressCleansingResultMessage"
})
public class TaxAreaResultType {

    @XmlElement(name = "Jurisdiction")
    protected List<JurisdictionType> jurisdiction;
    @XmlElement(name = "PostalAddress")
    protected List<PostalAddressType> postalAddress;
    @XmlElement(name = "Coordinates")
    protected List<CoordinatesType> coordinates;
    /**
     * Represents the result of the lookup process.
     * 
     */
    @XmlElement(name = "Status")
    protected List<TaxAreaResultType.Status> status;
    /**
     * The reason for the Address Cleansing failure.
     * 
     */
    @XmlElement(name = "AddressCleansingResultMessage")
    protected List<TaxAreaResultType.AddressCleansingResultMessage> addressCleansingResultMessage;
    /**
     * A Vertex-specific number that identifies a tax area.
     * 
     */
    @XmlAttribute(name = "taxAreaId")
    protected Integer taxAreaId;
    /**
     * A date that provides time perspective for a Tax Area lookup. Tax Area IDs returned
     *                     for the lookup are based on the jurisdiction boundaries in effect as of this date. Defaults to the
     *                     current date.
     * 
     */
    @XmlAttribute(name = "asOfDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar asOfDate;
    /**
     * Indicates the relative likelihood that a result of a tax area lookup is correct based
     *                     on the lookup criteria.
     * 
     */
    @XmlAttribute(name = "confidenceIndicator")
    protected Integer confidenceIndicator;

    /**
     * Gets the value of the jurisdiction property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jurisdiction property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getJurisdiction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JurisdictionType }
     * </p>
     * 
     * 
     * @return
     *     The value of the jurisdiction property.
     */
    public List<JurisdictionType> getJurisdiction() {
        if (jurisdiction == null) {
            jurisdiction = new ArrayList<>();
        }
        return this.jurisdiction;
    }

    /**
     * Gets the value of the postalAddress property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the postalAddress property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getPostalAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PostalAddressType }
     * </p>
     * 
     * 
     * @return
     *     The value of the postalAddress property.
     */
    public List<PostalAddressType> getPostalAddress() {
        if (postalAddress == null) {
            postalAddress = new ArrayList<>();
        }
        return this.postalAddress;
    }

    /**
     * Gets the value of the coordinates property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coordinates property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCoordinates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoordinatesType }
     * </p>
     * 
     * 
     * @return
     *     The value of the coordinates property.
     */
    public List<CoordinatesType> getCoordinates() {
        if (coordinates == null) {
            coordinates = new ArrayList<>();
        }
        return this.coordinates;
    }

    /**
     * Represents the result of the lookup process.
     * 
     * Gets the value of the status property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the status property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxAreaResultType.Status }
     * </p>
     * 
     * 
     * @return
     *     The value of the status property.
     */
    public List<TaxAreaResultType.Status> getStatus() {
        if (status == null) {
            status = new ArrayList<>();
        }
        return this.status;
    }

    /**
     * The reason for the Address Cleansing failure.
     * 
     * Gets the value of the addressCleansingResultMessage property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addressCleansingResultMessage property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getAddressCleansingResultMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxAreaResultType.AddressCleansingResultMessage }
     * </p>
     * 
     * 
     * @return
     *     The value of the addressCleansingResultMessage property.
     */
    public List<TaxAreaResultType.AddressCleansingResultMessage> getAddressCleansingResultMessage() {
        if (addressCleansingResultMessage == null) {
            addressCleansingResultMessage = new ArrayList<>();
        }
        return this.addressCleansingResultMessage;
    }

    /**
     * A Vertex-specific number that identifies a tax area.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTaxAreaId() {
        return taxAreaId;
    }

    /**
     * Sets the value of the taxAreaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getTaxAreaId()
     */
    public void setTaxAreaId(Integer value) {
        this.taxAreaId = value;
    }

    /**
     * A date that provides time perspective for a Tax Area lookup. Tax Area IDs returned
     *                     for the lookup are based on the jurisdiction boundaries in effect as of this date. Defaults to the
     *                     current date.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAsOfDate() {
        return asOfDate;
    }

    /**
     * Sets the value of the asOfDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     * @see #getAsOfDate()
     */
    public void setAsOfDate(XMLGregorianCalendar value) {
        this.asOfDate = value;
    }

    /**
     * Indicates the relative likelihood that a result of a tax area lookup is correct based
     *                     on the lookup criteria.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getConfidenceIndicator() {
        return confidenceIndicator;
    }

    /**
     * Sets the value of the confidenceIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getConfidenceIndicator()
     */
    public void setConfidenceIndicator(Integer value) {
        this.confidenceIndicator = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.w3.org/2001/XMLSchema>string">
     *       <attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       <attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class AddressCleansingResultMessage {

        @XmlValue
        protected String value;
        /**
         * The specific fault code for the Address Cleansing failure.
         * 
         */
        @XmlAttribute(name = "code")
        protected String code;
        /**
         * The type of the Address Cleansing result.
         * 
         */
        @XmlAttribute(name = "type")
        protected String type;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * The specific fault code for the Address Cleansing failure.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getCode()
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * The type of the Address Cleansing result.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getType()
         */
        public void setType(String value) {
            this.type = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.w3.org/2001/XMLSchema>string">
     *       <attribute name="lookupResult" use="required" type="{urn:vertexinc:o-series:tps:9:0}LookupResultType" />
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Status {

        @XmlValue
        protected String value;
        /**
         * The status of the Tax Area lookup.
         * 
         */
        @XmlAttribute(name = "lookupResult", required = true)
        protected LookupResultType lookupResult;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * The status of the Tax Area lookup.
         * 
         * @return
         *     possible object is
         *     {@link LookupResultType }
         *     
         */
        public LookupResultType getLookupResult() {
            return lookupResult;
        }

        /**
         * Sets the value of the lookupResult property.
         * 
         * @param value
         *     allowed object is
         *     {@link LookupResultType }
         *     
         * @see #getLookupResult()
         */
        public void setLookupResult(LookupResultType value) {
            this.lookupResult = value;
        }

    }

}
