//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Tax Area request type declaration.
 * 
 * <p>Java class for TaxAreaRequestType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="TaxAreaRequestType">
 *   <complexContent>
 *     <extension base="{urn:vertexinc:o-series:tps:9:0}TaxgisRequestType">
 *       <sequence>
 *         <element name="TaxAreaLookup" type="{urn:vertexinc:o-series:tps:9:0}TaxAreaLookupType" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxAreaRequestType", propOrder = {
    "taxAreaLookup"
})
public class TaxAreaRequestType
    extends TaxgisRequestType
{

    /**
     * The criteria to use in looking up the tax area. Use one of the following: TaxAreaId, PostalAddress, or ExternalJurisdiction.
     * 
     */
    @XmlElement(name = "TaxAreaLookup")
    protected TaxAreaLookupType taxAreaLookup;

    /**
     * The criteria to use in looking up the tax area. Use one of the following: TaxAreaId, PostalAddress, or ExternalJurisdiction.
     * 
     * @return
     *     possible object is
     *     {@link TaxAreaLookupType }
     *     
     */
    public TaxAreaLookupType getTaxAreaLookup() {
        return taxAreaLookup;
    }

    /**
     * Sets the value of the taxAreaLookup property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxAreaLookupType }
     *     
     * @see #getTaxAreaLookup()
     */
    public void setTaxAreaLookup(TaxAreaLookupType value) {
        this.taxAreaLookup = value;
    }

}
