//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Tax Area Response type structure
 * 
 * <p>Java class for TaxAreaResponseType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="TaxAreaResponseType">
 *   <complexContent>
 *     <extension base="{urn:vertexinc:o-series:tps:9:0}TaxgisResponseType">
 *       <sequence>
 *         <element name="TaxAreaResult" type="{urn:vertexinc:o-series:tps:9:0}TaxAreaResultType" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxAreaResponseType", propOrder = {
    "taxAreaResult"
})
public class TaxAreaResponseType
    extends TaxgisResponseType
{

    /**
     * A set of one or more geographic areas that correspond to a unique combination of tax jurisdictions where the tax area's boundaries are derived from the overlay of the geographic areas that form the domain of those jurisdictions.
     * 
     */
    @XmlElement(name = "TaxAreaResult")
    protected List<TaxAreaResultType> taxAreaResult;

    /**
     * A set of one or more geographic areas that correspond to a unique combination of tax jurisdictions where the tax area's boundaries are derived from the overlay of the geographic areas that form the domain of those jurisdictions.
     * 
     * Gets the value of the taxAreaResult property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxAreaResult property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getTaxAreaResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxAreaResultType }
     * </p>
     * 
     * 
     * @return
     *     The value of the taxAreaResult property.
     */
    public List<TaxAreaResultType> getTaxAreaResult() {
        if (taxAreaResult == null) {
            taxAreaResult = new ArrayList<>();
        }
        return this.taxAreaResult;
    }

}
