//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.28 at 02:15:16 PM IST 
//


package com.siteone.integration.webserviceclient.vertexclient;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaxCollectedFromPartyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TaxCollectedFromPartyType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="SELLER"/&gt;
 *     &lt;enumeration value="BUYER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TaxCollectedFromPartyType")
@XmlEnum
public enum TaxCollectedFromPartyType {


    /**
     * In Supplies transactions, the Seller is equivalent to the Taxpayer
     *                         responsible for collecting and remitting tax.
     *                     
     * 
     */
    SELLER,

    /**
     * In Sales tax or Value Added Tax Supplies transactions, the Buyer is
     *                         equivalent to the Customer receiving goods or services.
     *                     
     * 
     */
    BUYER;

    public String value() {
        return name();
    }

    public static TaxCollectedFromPartyType fromValue(String v) {
        return valueOf(v);
    }

}
