//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * Taxes calculated by the transaction processing system.
 * 
 * <p>Java class for TaxesType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="TaxesType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Jurisdiction" minOccurs="0">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<urn:vertexinc:o-series:tps:9:0>JurisdictionType">
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="AccumulateAsJurisdiction" minOccurs="0">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<urn:vertexinc:o-series:tps:9:0>JurisdictionType">
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="CalculatedTax" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
 *         <element name="EffectiveRate" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               <minInclusive value="0"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="TaxApportionmentRate" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               <minInclusive value="0"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="BasisReductionPercentage" minOccurs="0">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               <minInclusive value="0"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="Exempt" type="{urn:vertexinc:o-series:tps:9:0}MeasureType" minOccurs="0"/>
 *         <element name="NonTaxable" type="{urn:vertexinc:o-series:tps:9:0}MeasureType" minOccurs="0"/>
 *         <element name="Taxable" type="{urn:vertexinc:o-series:tps:9:0}MeasureType" minOccurs="0"/>
 *         <element name="ReportingBasis" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
 *         <element name="Imposition" minOccurs="0">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.w3.org/2001/XMLSchema>string">
 *                 <attribute name="userDefined" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 <attribute name="impositionId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}ImpositionType" minOccurs="0"/>
 *         <element name="AccumulateAsImposition" minOccurs="0">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.w3.org/2001/XMLSchema>string">
 *                 <attribute name="userDefined" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 <attribute name="impositionId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}AccumulateAsImpositionType" minOccurs="0"/>
 *         <element name="TaxRuleId" type="{urn:vertexinc:o-series:tps:9:0}RuleType" minOccurs="0"/>
 *         <element name="BasisRuleId" type="{urn:vertexinc:o-series:tps:9:0}RuleType" minOccurs="0"/>
 *         <element name="InclusionRuleId" type="{urn:vertexinc:o-series:tps:9:0}RuleType" minOccurs="0"/>
 *         <element name="MaxTaxRuleId" type="{urn:vertexinc:o-series:tps:9:0}RuleType" minOccurs="0"/>
 *         <element name="RecoverableRuleId" type="{urn:vertexinc:o-series:tps:9:0}RuleType" minOccurs="0"/>
 *         <element name="PostCalculationEvaluationRuleId" type="{urn:vertexinc:o-series:tps:9:0}RuleType" minOccurs="0"/>
 *         <element name="CreditRuleId" type="{urn:vertexinc:o-series:tps:9:0}RuleType" minOccurs="0"/>
 *         <element name="BasisApportionmentRuleId" type="{urn:vertexinc:o-series:tps:9:0}RuleType" minOccurs="0"/>
 *         <element name="TaxRateAdjustmentRuleId" type="{urn:vertexinc:o-series:tps:9:0}RuleType" minOccurs="0"/>
 *         <element name="TaxApportionmentRuleId" type="{urn:vertexinc:o-series:tps:9:0}RuleType" minOccurs="0"/>
 *         <element name="AccumulationRuleId" type="{urn:vertexinc:o-series:tps:9:0}RuleType" minOccurs="0"/>
 *         <element name="TelecomUnitConversionRuleId" type="{urn:vertexinc:o-series:tps:9:0}RuleType" minOccurs="0"/>
 *         <element name="ReportingBasisRuleId" type="{urn:vertexinc:o-series:tps:9:0}RuleType" minOccurs="0"/>
 *         <element name="CertificateNumber" minOccurs="0">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.w3.org/2001/XMLSchema>string">
 *                 <attribute name="certificateType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *         <element name="RecoverableAmount" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
 *         <element name="RecoverablePercent" type="{urn:vertexinc:o-series:tps:9:0}PercentType" minOccurs="0"/>
 *         <element name="BlockingRecoverablePercent" type="{urn:vertexinc:o-series:tps:9:0}PercentType" minOccurs="0"/>
 *         <element name="PartialExemptRecoverablePercent" type="{urn:vertexinc:o-series:tps:9:0}PercentType" minOccurs="0"/>
 *         <element name="UnrecoverableAmount" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
 *         <element name="FilingCurrencyAmounts" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element ref="{urn:vertexinc:o-series:tps:9:0}CurrencyConversion"/>
 *                   <element name="FilingCalculatedTax" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
 *                   <element name="FilingExempt" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
 *                   <element name="FilingNonTaxable" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
 *                   <element name="FilingTaxable" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
 *                   <element name="FilingRecoverableAmount" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
 *                   <element name="FilingUnrecoverableAmount" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="SellerRegistrationId" type="{urn:vertexinc:o-series:tps:9:0}RegistrationIdType" minOccurs="0"/>
 *         <element name="BuyerRegistrationId" type="{urn:vertexinc:o-series:tps:9:0}RegistrationIdType" minOccurs="0"/>
 *         <element name="OwnerRegistrationId" type="{urn:vertexinc:o-series:tps:9:0}RegistrationIdType" minOccurs="0"/>
 *         <element name="DispatcherRegistrationId" type="{urn:vertexinc:o-series:tps:9:0}RegistrationIdType" minOccurs="0"/>
 *         <element name="RecipientRegistrationId" type="{urn:vertexinc:o-series:tps:9:0}RegistrationIdType" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}InvoiceTextCode" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="SummaryInvoiceText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}InvoiceTexts" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}AssistedParameters" minOccurs="0"/>
 *         <element ref="{urn:vertexinc:o-series:tps:9:0}TaxRuleCurrencyConversionFactors" minOccurs="0"/>
 *         <element name="OriginalTax" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
 *         <element name="IncludedTax" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
 *         <element name="NominalRate" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
 *         <element name="MarkUpRate" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
 *         <element name="AccumulateAsLineType" minOccurs="0">
 *           <complexType>
 *             <simpleContent>
 *               <extension base="<http://www.w3.org/2001/XMLSchema>string">
 *                 <attribute name="userDefined" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               </extension>
 *             </simpleContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *       <attribute name="taxResult" type="{urn:vertexinc:o-series:tps:9:0}TaxResultCodeType" />
 *       <attribute name="taxType" type="{urn:vertexinc:o-series:tps:9:0}TaxingType" />
 *       <attribute name="maxTaxIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       <attribute name="situs" type="{urn:vertexinc:o-series:tps:9:0}TaxingLocationCodeType" />
 *       <attribute name="notRegisteredIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       <attribute name="inputOutputType" type="{urn:vertexinc:o-series:tps:9:0}InputOutputCodeType" />
 *       <attribute name="taxCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="vertexTaxCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="reasonCode" type="{urn:vertexinc:o-series:tps:9:0}ReasonCodeType" />
 *       <attribute name="filingCategoryCode">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *             <minInclusive value="1"/>
 *             <maxInclusive value="99999"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *       <attribute name="isService" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       <attribute name="rateClassification" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="taxCollectedFromParty" type="{urn:vertexinc:o-series:tps:9:0}TaxCollectedFromPartyType" />
 *       <attribute name="taxStructure" type="{urn:vertexinc:o-series:tps:9:0}TaxStructureCodeType" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxesType", propOrder = {
    "jurisdiction",
    "accumulateAsJurisdiction",
    "calculatedTax",
    "effectiveRate",
    "taxApportionmentRate",
    "basisReductionPercentage",
    "exempt",
    "nonTaxable",
    "taxable",
    "reportingBasis",
    "imposition",
    "impositionType",
    "accumulateAsImposition",
    "accumulateAsImpositionType",
    "taxRuleId",
    "basisRuleId",
    "inclusionRuleId",
    "maxTaxRuleId",
    "recoverableRuleId",
    "postCalculationEvaluationRuleId",
    "creditRuleId",
    "basisApportionmentRuleId",
    "taxRateAdjustmentRuleId",
    "taxApportionmentRuleId",
    "accumulationRuleId",
    "telecomUnitConversionRuleId",
    "reportingBasisRuleId",
    "certificateNumber",
    "recoverableAmount",
    "recoverablePercent",
    "blockingRecoverablePercent",
    "partialExemptRecoverablePercent",
    "unrecoverableAmount",
    "filingCurrencyAmounts",
    "sellerRegistrationId",
    "buyerRegistrationId",
    "ownerRegistrationId",
    "dispatcherRegistrationId",
    "recipientRegistrationId",
    "invoiceTextCode",
    "summaryInvoiceText",
    "invoiceTexts",
    "assistedParameters",
    "taxRuleCurrencyConversionFactors",
    "originalTax",
    "includedTax",
    "nominalRate",
    "markUpRate",
    "accumulateAsLineType"
})
public class TaxesType {

    /**
     * The name of jurisdiction to which a tax is applied.
     * 
     */
    @XmlElement(name = "Jurisdiction")
    protected TaxesType.Jurisdiction jurisdiction;
    /**
     * The name of jurisdiction to which the tax is accumulated to.
     * 
     */
    @XmlElement(name = "AccumulateAsJurisdiction")
    protected TaxesType.AccumulateAsJurisdiction accumulateAsJurisdiction;
    /**
     * Amount of tax calculated by the calculation engine.
     * 
     */
    @XmlElement(name = "CalculatedTax")
    protected BigDecimal calculatedTax;
    /**
     * For Buyer Input tax and Seller Import tax, this rate is calculated based on the
     *                         Extended Price and Tax Amount (Import or Input) passed in the Request message. If you total the
     *                         Extended Price and Tax Amounts before passing them in, this rate is an average.
     * 
     *                         For all other message types, this is the effective rate the system used to calculate tax.
     * 
     */
    @XmlElement(name = "EffectiveRate")
    protected BigDecimal effectiveRate;
    /**
     * The tax apportionment rate to apportion the calculated tax between two different
     *                         locaitons.
     * 
     */
    @XmlElement(name = "TaxApportionmentRate")
    protected BigDecimal taxApportionmentRate;
    /**
     * the percentage by which a basis amount is reduced in a tax calculation.
     * 
     */
    @XmlElement(name = "BasisReductionPercentage")
    protected BigDecimal basisReductionPercentage;
    /**
     * Amount or count of the line item not subject to tax due to exempt status.
     * 
     */
    @XmlElement(name = "Exempt")
    protected MeasureType exempt;
    /**
     * Amount or count of the line item not subject to tax due to nontaxable status.
     * 
     */
    @XmlElement(name = "NonTaxable")
    protected MeasureType nonTaxable;
    /**
     * Amount or count of the line item subject to tax.
     * 
     */
    @XmlElement(name = "Taxable")
    protected MeasureType taxable;
    /**
     * Amount subject to reporting basis.
     * 
     */
    @XmlElement(name = "ReportingBasis")
    protected BigDecimal reportingBasis;
    /**
     * The name of the imposition to which the relevant tax rule belongs. This is
     *                         assigned either by Vertex or by the user when setting up a user-defined imposition in the Vertex
     *                         Central user interface.
     * 
     */
    @XmlElement(name = "Imposition")
    protected TaxesType.Imposition imposition;
    /**
     * The type description that is assigned to the imposition.
     * 
     */
    @XmlElement(name = "ImpositionType")
    protected ImpositionType impositionType;
    /**
     * The name of the imposition to which the relevant tax rule belongs. This is
     *                         assigned either by Vertex or by the user when setting up a user-defined imposition in the Vertex
     *                         Central user interface.
     * 
     */
    @XmlElement(name = "AccumulateAsImposition")
    protected TaxesType.AccumulateAsImposition accumulateAsImposition;
    /**
     * The type description that is assigned to the accumulate as imposition.
     * 
     */
    @XmlElement(name = "AccumulateAsImpositionType")
    protected AccumulateAsImpositionType accumulateAsImpositionType;
    /**
     * An identifier for the tax rule that was used in tax calculation. This can be used
     *                         as a troubleshooting aid.
     * 
     */
    @XmlElement(name = "TaxRuleId")
    protected RuleType taxRuleId;
    /**
     * An identifier for the basis rule that was used in tax calculation. This can be
     *                         used as a troubleshooting aid.
     * 
     */
    @XmlElement(name = "BasisRuleId")
    protected RuleType basisRuleId;
    /**
     * An identifier for an inclusion rule.
     * 
     */
    @XmlElement(name = "InclusionRuleId")
    protected RuleType inclusionRuleId;
    /**
     * An identifier for the Max Tax rule that was used in tax calculation. This can be
     *                         used as a troubleshooting aid.
     * 
     */
    @XmlElement(name = "MaxTaxRuleId")
    protected RuleType maxTaxRuleId;
    /**
     * The identifier of the applicable VAT Recoverability Rule for the line item. This
     *                         Recoverability Rule determines
     *                         the percentage of input VAT that is deemed to be unrecoverable. This is an optional child
     *                         element of the Taxes element.
     * 
     */
    @XmlElement(name = "RecoverableRuleId")
    protected RuleType recoverableRuleId;
    /**
     * An identifier for the post calculation evaluation rule.
     * 
     */
    @XmlElement(name = "PostCalculationEvaluationRuleId")
    protected RuleType postCalculationEvaluationRuleId;
    /**
     * An identifier for the credit rule.
     * 
     */
    @XmlElement(name = "CreditRuleId")
    protected RuleType creditRuleId;
    /**
     * An identifier for a Basis Apportionment Rule. Apportionment rules are specific to
     *                         each taxpayer. Use this field to identify a user-defined rule that specifies apportionment rates
     *                         for each taxpayer.
     * 
     */
    @XmlElement(name = "BasisApportionmentRuleId")
    protected RuleType basisApportionmentRuleId;
    /**
     * An identifier for the tax rate adjustment rule.
     * 
     */
    @XmlElement(name = "TaxRateAdjustmentRuleId")
    protected RuleType taxRateAdjustmentRuleId;
    /**
     * An identifier for the tax apportionment rule.
     * 
     */
    @XmlElement(name = "TaxApportionmentRuleId")
    protected RuleType taxApportionmentRuleId;
    /**
     * An identifier for the accumulate rule.
     * 
     */
    @XmlElement(name = "AccumulationRuleId")
    protected RuleType accumulationRuleId;
    /**
     * An identifier for the telecommunication unit conversion rule.
     * 
     */
    @XmlElement(name = "TelecomUnitConversionRuleId")
    protected RuleType telecomUnitConversionRuleId;
    /**
     * An identifier for the reporting basis rule.
     * 
     */
    @XmlElement(name = "ReportingBasisRuleId")
    protected RuleType reportingBasisRuleId;
    /**
     * The certificate number associated with the line item tax.
     * 
     */
    @XmlElement(name = "CertificateNumber")
    protected TaxesType.CertificateNumber certificateNumber;
    /**
     * The amount of input or import tax that the buyer is able to recover on a
     *                         transaction. This is the amount that the Buyer puts on their returns in order to recover these
     *                         funds.
     * 
     */
    @XmlElement(name = "RecoverableAmount")
    protected BigDecimal recoverableAmount;
    /**
     * The percent of the tax that is recoverable, as calculated based on passed in
     *                         recoverable amount and tax. Expressed as a decimal: 1.0 for 100%, .8 for 80%, .5 for 50%, and so
     *                         on.
     * 
     */
    @XmlElement(name = "RecoverablePercent")
    protected BigDecimal recoverablePercent;
    /**
     * The recoverable override percentage
     *                         of the blocking override on the Input Tax level.
     * 
     */
    @XmlElement(name = "BlockingRecoverablePercent")
    protected BigDecimal blockingRecoverablePercent;
    /**
     * The recoverable percentage of a partial exemption. This field is populated only
     *                         for transactions with a tax type of Value Added Tax.
     * 
     */
    @XmlElement(name = "PartialExemptRecoverablePercent")
    protected BigDecimal partialExemptRecoverablePercent;
    /**
     * The amount of input or import tax that the taxpayer is not able to recover. It is
     *                         lost, which is a true cost to the taxpayer.
     * 
     */
    @XmlElement(name = "UnrecoverableAmount")
    protected BigDecimal unrecoverableAmount;
    /**
     * A grouping of filing currency converted taxability amounts.
     * 
     */
    @XmlElement(name = "FilingCurrencyAmounts")
    protected TaxesType.FilingCurrencyAmounts filingCurrencyAmounts;
    /**
     * The Registration ID for the Seller associated with this line item tax.
     * 
     */
    @XmlElement(name = "SellerRegistrationId")
    protected String sellerRegistrationId;
    /**
     * The Registration ID for the Buyer associated with this line item tax.
     * 
     */
    @XmlElement(name = "BuyerRegistrationId")
    protected String buyerRegistrationId;
    /**
     * The Registration ID for the Owner associated with this line item tax.
     * 
     */
    @XmlElement(name = "OwnerRegistrationId")
    protected String ownerRegistrationId;
    /**
     * The Registration ID for the Dispatcher associated with this line item tax.
     * 
     */
    @XmlElement(name = "DispatcherRegistrationId")
    protected String dispatcherRegistrationId;
    /**
     * The Registration ID for the Recipient associated with this line item tax.
     * 
     */
    @XmlElement(name = "RecipientRegistrationId")
    protected String recipientRegistrationId;
    /**
     * Indicator that alerts the host system of the need to add invoice text of a specific type
     *           to a line item. For a list of the codes and their meanings, see the Supporting Information section in
     *           the XML Integration Guide. Note: This transaction is considered to involve a VAT group if a value of 2
     *           (Intra-EU Notice) is returned, the POS jurisdiction is an EU country, and the buyer and seller have the
     *           same registration number.
     * 
     */
    @XmlElement(name = "InvoiceTextCode")
    protected List<BigInteger> invoiceTextCode;
    /**
     * Additional information about a tax, to be returned to your host system after tax
     *                   calculation. To supply a value for this field, you need to set up a post-calculation Tax Assist
     *                   rule. Note: The text you add to this field is not stored in the Tax Journal.
     * 
     */
    @XmlElement(name = "SummaryInvoiceText")
    protected String summaryInvoiceText;
    @XmlElement(name = "InvoiceTexts")
    protected InvoiceTextsType invoiceTexts;
    @XmlElement(name = "AssistedParameters")
    protected AssistedParametersType assistedParameters;
    /**
     * A list of tax rule currency conversion factors.
     * 
     */
    @XmlElement(name = "TaxRuleCurrencyConversionFactors")
    protected TaxRuleCurrencyConversionFactors taxRuleCurrencyConversionFactors;
    /**
     * The tax amount before applying a tax credit rule.
     * 
     */
    @XmlElement(name = "OriginalTax")
    protected BigDecimal originalTax;
    /**
     * The total tax amount included in the basis.
     * 
     */
    @XmlElement(name = "IncludedTax")
    protected BigDecimal includedTax;
    /**
     * The original ICMS tax rate for origin and destination states.
     * 
     */
    @XmlElement(name = "NominalRate")
    protected BigDecimal nominalRate;
    /**
     * The Mark up rate.
     * 
     */
    @XmlElement(name = "MarkUpRate")
    protected BigDecimal markUpRate;
    /**
     * Accumulate as Line Type of a telecom line.
     * 
     */
    @XmlElement(name = "AccumulateAsLineType")
    protected TaxesType.AccumulateAsLineType accumulateAsLineType;
    /**
     * System determination of taxable status based on situs and item type. Note: Tax
     *                     amounts with a value of Deferred are payable at a later time and should NOT be written to the
     *                     invoice.
     * 
     */
    @XmlAttribute(name = "taxResult")
    protected TaxResultCodeType taxResult;
    /**
     * System determined tax type, based on situs, transaction type, and party role type
     *                     (perspective).
     * 
     */
    @XmlAttribute(name = "taxType")
    protected TaxingType taxType;
    /**
     * Indicates that max tax was applied to this line item of the invoice.
     * 
     */
    @XmlAttribute(name = "maxTaxIndicator")
    protected Boolean maxTaxIndicator;
    /**
     * The situs determined by the calculation engine for the line item.
     * 
     */
    @XmlAttribute(name = "situs")
    protected TaxingLocationCodeType situs;
    /**
     * Indicates that the taxpayer company is not registered in the taxing jurisdiction.
     * 
     */
    @XmlAttribute(name = "notRegisteredIndicator")
    protected Boolean notRegisteredIndicator;
    /**
     * Identifies whether tax is Input VAT, Output VAT, or both according to the perspective
     *                     of the transaction to allow for Reverse Charges.
     * 
     */
    @XmlAttribute(name = "inputOutputType")
    protected InputOutputCodeType inputOutputType;
    /**
     * A user-defined code for the tax, to be returned to your host system after tax
     *                     calculation. To return a value for this field, set up a post-calculation Tax Assist rule.
     * 
     */
    @XmlAttribute(name = "taxCode")
    protected String taxCode;
    /**
     * A code that can be used to classify the transaction at the tax level for reporting or
     *                     tax return filing purposes. The code is generated by the Calculation Engine for each line item after
     *                     tax calculation. It can be used as a filter for reports or as an input for post-calculation Tax
     *                     Assist rules. For detailed information about the contents of the code, see the Supporting
     *                     Information section of the XML Integration Guide.
     * 
     */
    @XmlAttribute(name = "vertexTaxCode")
    protected String vertexTaxCode;
    /**
     * A code that indicates the reason for the exception that was applied to this tax.
     *                     Note: For a tax with multiple tiers, O Series returns the reason code associated with the largest
     *                     basis amount. Note: To pass a standard (i.e., not user-defined) single-digit reason code, pad the
     *                     code to four digits. Refer to the Supporting Information section of the XML Integration Guide for
     *                     information on exemption and deduction reason codes.
     * 
     */
    @XmlAttribute(name = "reasonCode")
    protected String reasonCode;
    /**
     * Provides additional classification of the transaction for tax returns and reporting.
     *                     Codes are jurisdiction-specific. Note: For a tax with multiple tiers, O Series returns the filing
     *                     category code associated with the largest basis amount.
     * 
     */
    @XmlAttribute(name = "filingCategoryCode")
    protected Integer filingCategoryCode;
    /**
     * Indicates whether or not the product is a service.
     * 
     */
    @XmlAttribute(name = "isService")
    protected Boolean isService;
    /**
     * A Vertex-defined classification of the applicable tax rule for returns filing
     *                     purposes. Possible values are: Luxury Rate, Standard Rate, Reduced Rate 1, Reduced Rate 2, Reduced
     *                     Rate 3, Reduced Rate 4, Reduced Rate 5, User Defined, Zero Rate, Outside the Scope.
     * 
     */
    @XmlAttribute(name = "rateClassification")
    protected String rateClassification;
    /**
     * The party who is responsible for the sales tax. Note: Tax amounts with a value of
     *                     Seller cannot be charged to your customer and should NOT be written to the invoice.
     * 
     */
    @XmlAttribute(name = "taxCollectedFromParty")
    protected TaxCollectedFromPartyType taxCollectedFromParty;
    /**
     * Specifies the applicable tax structure when the transaction includes a flat
     *                     fee or quantity-based fee. Valid values are
     *                     BRACKET, FLAT_TAX, QUANTITY, SINGLE_RATE, TIERED, QUANTITY_TIERED, QUANTITY_RATE_TIERED,
     *                     TIERED_MODIFIER, QUANTITY_TIERED_MODIFIER, QUANTITY_RATE_TIERED_MODIFIER, QUANTITY_TIERED_FLAT,
     *                     TIERED_FLAT and QUANTITY_RATE_TIERED_EQUIVALENT.
     * 
     */
    @XmlAttribute(name = "taxStructure")
    protected TaxStructureCodeType taxStructure;

    /**
     * The name of jurisdiction to which a tax is applied.
     * 
     * @return
     *     possible object is
     *     {@link TaxesType.Jurisdiction }
     *     
     */
    public TaxesType.Jurisdiction getJurisdiction() {
        return jurisdiction;
    }

    /**
     * Sets the value of the jurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxesType.Jurisdiction }
     *     
     * @see #getJurisdiction()
     */
    public void setJurisdiction(TaxesType.Jurisdiction value) {
        this.jurisdiction = value;
    }

    /**
     * The name of jurisdiction to which the tax is accumulated to.
     * 
     * @return
     *     possible object is
     *     {@link TaxesType.AccumulateAsJurisdiction }
     *     
     */
    public TaxesType.AccumulateAsJurisdiction getAccumulateAsJurisdiction() {
        return accumulateAsJurisdiction;
    }

    /**
     * Sets the value of the accumulateAsJurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxesType.AccumulateAsJurisdiction }
     *     
     * @see #getAccumulateAsJurisdiction()
     */
    public void setAccumulateAsJurisdiction(TaxesType.AccumulateAsJurisdiction value) {
        this.accumulateAsJurisdiction = value;
    }

    /**
     * Amount of tax calculated by the calculation engine.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCalculatedTax() {
        return calculatedTax;
    }

    /**
     * Sets the value of the calculatedTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getCalculatedTax()
     */
    public void setCalculatedTax(BigDecimal value) {
        this.calculatedTax = value;
    }

    /**
     * For Buyer Input tax and Seller Import tax, this rate is calculated based on the
     *                         Extended Price and Tax Amount (Import or Input) passed in the Request message. If you total the
     *                         Extended Price and Tax Amounts before passing them in, this rate is an average.
     * 
     *                         For all other message types, this is the effective rate the system used to calculate tax.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEffectiveRate() {
        return effectiveRate;
    }

    /**
     * Sets the value of the effectiveRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getEffectiveRate()
     */
    public void setEffectiveRate(BigDecimal value) {
        this.effectiveRate = value;
    }

    /**
     * The tax apportionment rate to apportion the calculated tax between two different
     *                         locaitons.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxApportionmentRate() {
        return taxApportionmentRate;
    }

    /**
     * Sets the value of the taxApportionmentRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getTaxApportionmentRate()
     */
    public void setTaxApportionmentRate(BigDecimal value) {
        this.taxApportionmentRate = value;
    }

    /**
     * the percentage by which a basis amount is reduced in a tax calculation.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBasisReductionPercentage() {
        return basisReductionPercentage;
    }

    /**
     * Sets the value of the basisReductionPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getBasisReductionPercentage()
     */
    public void setBasisReductionPercentage(BigDecimal value) {
        this.basisReductionPercentage = value;
    }

    /**
     * Amount or count of the line item not subject to tax due to exempt status.
     * 
     * @return
     *     possible object is
     *     {@link MeasureType }
     *     
     */
    public MeasureType getExempt() {
        return exempt;
    }

    /**
     * Sets the value of the exempt property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureType }
     *     
     * @see #getExempt()
     */
    public void setExempt(MeasureType value) {
        this.exempt = value;
    }

    /**
     * Amount or count of the line item not subject to tax due to nontaxable status.
     * 
     * @return
     *     possible object is
     *     {@link MeasureType }
     *     
     */
    public MeasureType getNonTaxable() {
        return nonTaxable;
    }

    /**
     * Sets the value of the nonTaxable property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureType }
     *     
     * @see #getNonTaxable()
     */
    public void setNonTaxable(MeasureType value) {
        this.nonTaxable = value;
    }

    /**
     * Amount or count of the line item subject to tax.
     * 
     * @return
     *     possible object is
     *     {@link MeasureType }
     *     
     */
    public MeasureType getTaxable() {
        return taxable;
    }

    /**
     * Sets the value of the taxable property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureType }
     *     
     * @see #getTaxable()
     */
    public void setTaxable(MeasureType value) {
        this.taxable = value;
    }

    /**
     * Amount subject to reporting basis.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReportingBasis() {
        return reportingBasis;
    }

    /**
     * Sets the value of the reportingBasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getReportingBasis()
     */
    public void setReportingBasis(BigDecimal value) {
        this.reportingBasis = value;
    }

    /**
     * The name of the imposition to which the relevant tax rule belongs. This is
     *                         assigned either by Vertex or by the user when setting up a user-defined imposition in the Vertex
     *                         Central user interface.
     * 
     * @return
     *     possible object is
     *     {@link TaxesType.Imposition }
     *     
     */
    public TaxesType.Imposition getImposition() {
        return imposition;
    }

    /**
     * Sets the value of the imposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxesType.Imposition }
     *     
     * @see #getImposition()
     */
    public void setImposition(TaxesType.Imposition value) {
        this.imposition = value;
    }

    /**
     * The type description that is assigned to the imposition.
     * 
     * @return
     *     possible object is
     *     {@link ImpositionType }
     *     
     */
    public ImpositionType getImpositionType() {
        return impositionType;
    }

    /**
     * Sets the value of the impositionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImpositionType }
     *     
     * @see #getImpositionType()
     */
    public void setImpositionType(ImpositionType value) {
        this.impositionType = value;
    }

    /**
     * The name of the imposition to which the relevant tax rule belongs. This is
     *                         assigned either by Vertex or by the user when setting up a user-defined imposition in the Vertex
     *                         Central user interface.
     * 
     * @return
     *     possible object is
     *     {@link TaxesType.AccumulateAsImposition }
     *     
     */
    public TaxesType.AccumulateAsImposition getAccumulateAsImposition() {
        return accumulateAsImposition;
    }

    /**
     * Sets the value of the accumulateAsImposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxesType.AccumulateAsImposition }
     *     
     * @see #getAccumulateAsImposition()
     */
    public void setAccumulateAsImposition(TaxesType.AccumulateAsImposition value) {
        this.accumulateAsImposition = value;
    }

    /**
     * The type description that is assigned to the accumulate as imposition.
     * 
     * @return
     *     possible object is
     *     {@link AccumulateAsImpositionType }
     *     
     */
    public AccumulateAsImpositionType getAccumulateAsImpositionType() {
        return accumulateAsImpositionType;
    }

    /**
     * Sets the value of the accumulateAsImpositionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccumulateAsImpositionType }
     *     
     * @see #getAccumulateAsImpositionType()
     */
    public void setAccumulateAsImpositionType(AccumulateAsImpositionType value) {
        this.accumulateAsImpositionType = value;
    }

    /**
     * An identifier for the tax rule that was used in tax calculation. This can be used
     *                         as a troubleshooting aid.
     * 
     * @return
     *     possible object is
     *     {@link RuleType }
     *     
     */
    public RuleType getTaxRuleId() {
        return taxRuleId;
    }

    /**
     * Sets the value of the taxRuleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleType }
     *     
     * @see #getTaxRuleId()
     */
    public void setTaxRuleId(RuleType value) {
        this.taxRuleId = value;
    }

    /**
     * An identifier for the basis rule that was used in tax calculation. This can be
     *                         used as a troubleshooting aid.
     * 
     * @return
     *     possible object is
     *     {@link RuleType }
     *     
     */
    public RuleType getBasisRuleId() {
        return basisRuleId;
    }

    /**
     * Sets the value of the basisRuleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleType }
     *     
     * @see #getBasisRuleId()
     */
    public void setBasisRuleId(RuleType value) {
        this.basisRuleId = value;
    }

    /**
     * An identifier for an inclusion rule.
     * 
     * @return
     *     possible object is
     *     {@link RuleType }
     *     
     */
    public RuleType getInclusionRuleId() {
        return inclusionRuleId;
    }

    /**
     * Sets the value of the inclusionRuleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleType }
     *     
     * @see #getInclusionRuleId()
     */
    public void setInclusionRuleId(RuleType value) {
        this.inclusionRuleId = value;
    }

    /**
     * An identifier for the Max Tax rule that was used in tax calculation. This can be
     *                         used as a troubleshooting aid.
     * 
     * @return
     *     possible object is
     *     {@link RuleType }
     *     
     */
    public RuleType getMaxTaxRuleId() {
        return maxTaxRuleId;
    }

    /**
     * Sets the value of the maxTaxRuleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleType }
     *     
     * @see #getMaxTaxRuleId()
     */
    public void setMaxTaxRuleId(RuleType value) {
        this.maxTaxRuleId = value;
    }

    /**
     * The identifier of the applicable VAT Recoverability Rule for the line item. This
     *                         Recoverability Rule determines
     *                         the percentage of input VAT that is deemed to be unrecoverable. This is an optional child
     *                         element of the Taxes element.
     * 
     * @return
     *     possible object is
     *     {@link RuleType }
     *     
     */
    public RuleType getRecoverableRuleId() {
        return recoverableRuleId;
    }

    /**
     * Sets the value of the recoverableRuleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleType }
     *     
     * @see #getRecoverableRuleId()
     */
    public void setRecoverableRuleId(RuleType value) {
        this.recoverableRuleId = value;
    }

    /**
     * An identifier for the post calculation evaluation rule.
     * 
     * @return
     *     possible object is
     *     {@link RuleType }
     *     
     */
    public RuleType getPostCalculationEvaluationRuleId() {
        return postCalculationEvaluationRuleId;
    }

    /**
     * Sets the value of the postCalculationEvaluationRuleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleType }
     *     
     * @see #getPostCalculationEvaluationRuleId()
     */
    public void setPostCalculationEvaluationRuleId(RuleType value) {
        this.postCalculationEvaluationRuleId = value;
    }

    /**
     * An identifier for the credit rule.
     * 
     * @return
     *     possible object is
     *     {@link RuleType }
     *     
     */
    public RuleType getCreditRuleId() {
        return creditRuleId;
    }

    /**
     * Sets the value of the creditRuleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleType }
     *     
     * @see #getCreditRuleId()
     */
    public void setCreditRuleId(RuleType value) {
        this.creditRuleId = value;
    }

    /**
     * An identifier for a Basis Apportionment Rule. Apportionment rules are specific to
     *                         each taxpayer. Use this field to identify a user-defined rule that specifies apportionment rates
     *                         for each taxpayer.
     * 
     * @return
     *     possible object is
     *     {@link RuleType }
     *     
     */
    public RuleType getBasisApportionmentRuleId() {
        return basisApportionmentRuleId;
    }

    /**
     * Sets the value of the basisApportionmentRuleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleType }
     *     
     * @see #getBasisApportionmentRuleId()
     */
    public void setBasisApportionmentRuleId(RuleType value) {
        this.basisApportionmentRuleId = value;
    }

    /**
     * An identifier for the tax rate adjustment rule.
     * 
     * @return
     *     possible object is
     *     {@link RuleType }
     *     
     */
    public RuleType getTaxRateAdjustmentRuleId() {
        return taxRateAdjustmentRuleId;
    }

    /**
     * Sets the value of the taxRateAdjustmentRuleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleType }
     *     
     * @see #getTaxRateAdjustmentRuleId()
     */
    public void setTaxRateAdjustmentRuleId(RuleType value) {
        this.taxRateAdjustmentRuleId = value;
    }

    /**
     * An identifier for the tax apportionment rule.
     * 
     * @return
     *     possible object is
     *     {@link RuleType }
     *     
     */
    public RuleType getTaxApportionmentRuleId() {
        return taxApportionmentRuleId;
    }

    /**
     * Sets the value of the taxApportionmentRuleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleType }
     *     
     * @see #getTaxApportionmentRuleId()
     */
    public void setTaxApportionmentRuleId(RuleType value) {
        this.taxApportionmentRuleId = value;
    }

    /**
     * An identifier for the accumulate rule.
     * 
     * @return
     *     possible object is
     *     {@link RuleType }
     *     
     */
    public RuleType getAccumulationRuleId() {
        return accumulationRuleId;
    }

    /**
     * Sets the value of the accumulationRuleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleType }
     *     
     * @see #getAccumulationRuleId()
     */
    public void setAccumulationRuleId(RuleType value) {
        this.accumulationRuleId = value;
    }

    /**
     * An identifier for the telecommunication unit conversion rule.
     * 
     * @return
     *     possible object is
     *     {@link RuleType }
     *     
     */
    public RuleType getTelecomUnitConversionRuleId() {
        return telecomUnitConversionRuleId;
    }

    /**
     * Sets the value of the telecomUnitConversionRuleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleType }
     *     
     * @see #getTelecomUnitConversionRuleId()
     */
    public void setTelecomUnitConversionRuleId(RuleType value) {
        this.telecomUnitConversionRuleId = value;
    }

    /**
     * An identifier for the reporting basis rule.
     * 
     * @return
     *     possible object is
     *     {@link RuleType }
     *     
     */
    public RuleType getReportingBasisRuleId() {
        return reportingBasisRuleId;
    }

    /**
     * Sets the value of the reportingBasisRuleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleType }
     *     
     * @see #getReportingBasisRuleId()
     */
    public void setReportingBasisRuleId(RuleType value) {
        this.reportingBasisRuleId = value;
    }

    /**
     * The certificate number associated with the line item tax.
     * 
     * @return
     *     possible object is
     *     {@link TaxesType.CertificateNumber }
     *     
     */
    public TaxesType.CertificateNumber getCertificateNumber() {
        return certificateNumber;
    }

    /**
     * Sets the value of the certificateNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxesType.CertificateNumber }
     *     
     * @see #getCertificateNumber()
     */
    public void setCertificateNumber(TaxesType.CertificateNumber value) {
        this.certificateNumber = value;
    }

    /**
     * The amount of input or import tax that the buyer is able to recover on a
     *                         transaction. This is the amount that the Buyer puts on their returns in order to recover these
     *                         funds.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRecoverableAmount() {
        return recoverableAmount;
    }

    /**
     * Sets the value of the recoverableAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getRecoverableAmount()
     */
    public void setRecoverableAmount(BigDecimal value) {
        this.recoverableAmount = value;
    }

    /**
     * The percent of the tax that is recoverable, as calculated based on passed in
     *                         recoverable amount and tax. Expressed as a decimal: 1.0 for 100%, .8 for 80%, .5 for 50%, and so
     *                         on.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRecoverablePercent() {
        return recoverablePercent;
    }

    /**
     * Sets the value of the recoverablePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getRecoverablePercent()
     */
    public void setRecoverablePercent(BigDecimal value) {
        this.recoverablePercent = value;
    }

    /**
     * The recoverable override percentage
     *                         of the blocking override on the Input Tax level.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBlockingRecoverablePercent() {
        return blockingRecoverablePercent;
    }

    /**
     * Sets the value of the blockingRecoverablePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getBlockingRecoverablePercent()
     */
    public void setBlockingRecoverablePercent(BigDecimal value) {
        this.blockingRecoverablePercent = value;
    }

    /**
     * The recoverable percentage of a partial exemption. This field is populated only
     *                         for transactions with a tax type of Value Added Tax.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPartialExemptRecoverablePercent() {
        return partialExemptRecoverablePercent;
    }

    /**
     * Sets the value of the partialExemptRecoverablePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getPartialExemptRecoverablePercent()
     */
    public void setPartialExemptRecoverablePercent(BigDecimal value) {
        this.partialExemptRecoverablePercent = value;
    }

    /**
     * The amount of input or import tax that the taxpayer is not able to recover. It is
     *                         lost, which is a true cost to the taxpayer.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnrecoverableAmount() {
        return unrecoverableAmount;
    }

    /**
     * Sets the value of the unrecoverableAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getUnrecoverableAmount()
     */
    public void setUnrecoverableAmount(BigDecimal value) {
        this.unrecoverableAmount = value;
    }

    /**
     * A grouping of filing currency converted taxability amounts.
     * 
     * @return
     *     possible object is
     *     {@link TaxesType.FilingCurrencyAmounts }
     *     
     */
    public TaxesType.FilingCurrencyAmounts getFilingCurrencyAmounts() {
        return filingCurrencyAmounts;
    }

    /**
     * Sets the value of the filingCurrencyAmounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxesType.FilingCurrencyAmounts }
     *     
     * @see #getFilingCurrencyAmounts()
     */
    public void setFilingCurrencyAmounts(TaxesType.FilingCurrencyAmounts value) {
        this.filingCurrencyAmounts = value;
    }

    /**
     * The Registration ID for the Seller associated with this line item tax.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerRegistrationId() {
        return sellerRegistrationId;
    }

    /**
     * Sets the value of the sellerRegistrationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSellerRegistrationId()
     */
    public void setSellerRegistrationId(String value) {
        this.sellerRegistrationId = value;
    }

    /**
     * The Registration ID for the Buyer associated with this line item tax.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerRegistrationId() {
        return buyerRegistrationId;
    }

    /**
     * Sets the value of the buyerRegistrationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getBuyerRegistrationId()
     */
    public void setBuyerRegistrationId(String value) {
        this.buyerRegistrationId = value;
    }

    /**
     * The Registration ID for the Owner associated with this line item tax.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerRegistrationId() {
        return ownerRegistrationId;
    }

    /**
     * Sets the value of the ownerRegistrationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getOwnerRegistrationId()
     */
    public void setOwnerRegistrationId(String value) {
        this.ownerRegistrationId = value;
    }

    /**
     * The Registration ID for the Dispatcher associated with this line item tax.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispatcherRegistrationId() {
        return dispatcherRegistrationId;
    }

    /**
     * Sets the value of the dispatcherRegistrationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getDispatcherRegistrationId()
     */
    public void setDispatcherRegistrationId(String value) {
        this.dispatcherRegistrationId = value;
    }

    /**
     * The Registration ID for the Recipient associated with this line item tax.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipientRegistrationId() {
        return recipientRegistrationId;
    }

    /**
     * Sets the value of the recipientRegistrationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getRecipientRegistrationId()
     */
    public void setRecipientRegistrationId(String value) {
        this.recipientRegistrationId = value;
    }

    /**
     * Indicator that alerts the host system of the need to add invoice text of a specific type
     *           to a line item. For a list of the codes and their meanings, see the Supporting Information section in
     *           the XML Integration Guide. Note: This transaction is considered to involve a VAT group if a value of 2
     *           (Intra-EU Notice) is returned, the POS jurisdiction is an EU country, and the buyer and seller have the
     *           same registration number.
     * 
     * Gets the value of the invoiceTextCode property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the invoiceTextCode property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getInvoiceTextCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigInteger }
     * </p>
     * 
     * 
     * @return
     *     The value of the invoiceTextCode property.
     */
    public List<BigInteger> getInvoiceTextCode() {
        if (invoiceTextCode == null) {
            invoiceTextCode = new ArrayList<>();
        }
        return this.invoiceTextCode;
    }

    /**
     * Additional information about a tax, to be returned to your host system after tax
     *                   calculation. To supply a value for this field, you need to set up a post-calculation Tax Assist
     *                   rule. Note: The text you add to this field is not stored in the Tax Journal.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummaryInvoiceText() {
        return summaryInvoiceText;
    }

    /**
     * Sets the value of the summaryInvoiceText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSummaryInvoiceText()
     */
    public void setSummaryInvoiceText(String value) {
        this.summaryInvoiceText = value;
    }

    /**
     * Gets the value of the invoiceTexts property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceTextsType }
     *     
     */
    public InvoiceTextsType getInvoiceTexts() {
        return invoiceTexts;
    }

    /**
     * Sets the value of the invoiceTexts property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceTextsType }
     *     
     */
    public void setInvoiceTexts(InvoiceTextsType value) {
        this.invoiceTexts = value;
    }

    /**
     * Gets the value of the assistedParameters property.
     * 
     * @return
     *     possible object is
     *     {@link AssistedParametersType }
     *     
     */
    public AssistedParametersType getAssistedParameters() {
        return assistedParameters;
    }

    /**
     * Sets the value of the assistedParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssistedParametersType }
     *     
     */
    public void setAssistedParameters(AssistedParametersType value) {
        this.assistedParameters = value;
    }

    /**
     * A list of tax rule currency conversion factors.
     * 
     * @return
     *     possible object is
     *     {@link TaxRuleCurrencyConversionFactors }
     *     
     */
    public TaxRuleCurrencyConversionFactors getTaxRuleCurrencyConversionFactors() {
        return taxRuleCurrencyConversionFactors;
    }

    /**
     * Sets the value of the taxRuleCurrencyConversionFactors property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxRuleCurrencyConversionFactors }
     *     
     * @see #getTaxRuleCurrencyConversionFactors()
     */
    public void setTaxRuleCurrencyConversionFactors(TaxRuleCurrencyConversionFactors value) {
        this.taxRuleCurrencyConversionFactors = value;
    }

    /**
     * The tax amount before applying a tax credit rule.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOriginalTax() {
        return originalTax;
    }

    /**
     * Sets the value of the originalTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getOriginalTax()
     */
    public void setOriginalTax(BigDecimal value) {
        this.originalTax = value;
    }

    /**
     * The total tax amount included in the basis.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncludedTax() {
        return includedTax;
    }

    /**
     * Sets the value of the includedTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getIncludedTax()
     */
    public void setIncludedTax(BigDecimal value) {
        this.includedTax = value;
    }

    /**
     * The original ICMS tax rate for origin and destination states.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNominalRate() {
        return nominalRate;
    }

    /**
     * Sets the value of the nominalRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getNominalRate()
     */
    public void setNominalRate(BigDecimal value) {
        this.nominalRate = value;
    }

    /**
     * The Mark up rate.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMarkUpRate() {
        return markUpRate;
    }

    /**
     * Sets the value of the markUpRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     * @see #getMarkUpRate()
     */
    public void setMarkUpRate(BigDecimal value) {
        this.markUpRate = value;
    }

    /**
     * Accumulate as Line Type of a telecom line.
     * 
     * @return
     *     possible object is
     *     {@link TaxesType.AccumulateAsLineType }
     *     
     */
    public TaxesType.AccumulateAsLineType getAccumulateAsLineType() {
        return accumulateAsLineType;
    }

    /**
     * Sets the value of the accumulateAsLineType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxesType.AccumulateAsLineType }
     *     
     * @see #getAccumulateAsLineType()
     */
    public void setAccumulateAsLineType(TaxesType.AccumulateAsLineType value) {
        this.accumulateAsLineType = value;
    }

    /**
     * System determination of taxable status based on situs and item type. Note: Tax
     *                     amounts with a value of Deferred are payable at a later time and should NOT be written to the
     *                     invoice.
     * 
     * @return
     *     possible object is
     *     {@link TaxResultCodeType }
     *     
     */
    public TaxResultCodeType getTaxResult() {
        return taxResult;
    }

    /**
     * Sets the value of the taxResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxResultCodeType }
     *     
     * @see #getTaxResult()
     */
    public void setTaxResult(TaxResultCodeType value) {
        this.taxResult = value;
    }

    /**
     * System determined tax type, based on situs, transaction type, and party role type
     *                     (perspective).
     * 
     * @return
     *     possible object is
     *     {@link TaxingType }
     *     
     */
    public TaxingType getTaxType() {
        return taxType;
    }

    /**
     * Sets the value of the taxType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxingType }
     *     
     * @see #getTaxType()
     */
    public void setTaxType(TaxingType value) {
        this.taxType = value;
    }

    /**
     * Indicates that max tax was applied to this line item of the invoice.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMaxTaxIndicator() {
        return maxTaxIndicator;
    }

    /**
     * Sets the value of the maxTaxIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #isMaxTaxIndicator()
     */
    public void setMaxTaxIndicator(Boolean value) {
        this.maxTaxIndicator = value;
    }

    /**
     * The situs determined by the calculation engine for the line item.
     * 
     * @return
     *     possible object is
     *     {@link TaxingLocationCodeType }
     *     
     */
    public TaxingLocationCodeType getSitus() {
        return situs;
    }

    /**
     * Sets the value of the situs property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxingLocationCodeType }
     *     
     * @see #getSitus()
     */
    public void setSitus(TaxingLocationCodeType value) {
        this.situs = value;
    }

    /**
     * Indicates that the taxpayer company is not registered in the taxing jurisdiction.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNotRegisteredIndicator() {
        return notRegisteredIndicator;
    }

    /**
     * Sets the value of the notRegisteredIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #isNotRegisteredIndicator()
     */
    public void setNotRegisteredIndicator(Boolean value) {
        this.notRegisteredIndicator = value;
    }

    /**
     * Identifies whether tax is Input VAT, Output VAT, or both according to the perspective
     *                     of the transaction to allow for Reverse Charges.
     * 
     * @return
     *     possible object is
     *     {@link InputOutputCodeType }
     *     
     */
    public InputOutputCodeType getInputOutputType() {
        return inputOutputType;
    }

    /**
     * Sets the value of the inputOutputType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputOutputCodeType }
     *     
     * @see #getInputOutputType()
     */
    public void setInputOutputType(InputOutputCodeType value) {
        this.inputOutputType = value;
    }

    /**
     * A user-defined code for the tax, to be returned to your host system after tax
     *                     calculation. To return a value for this field, set up a post-calculation Tax Assist rule.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxCode() {
        return taxCode;
    }

    /**
     * Sets the value of the taxCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getTaxCode()
     */
    public void setTaxCode(String value) {
        this.taxCode = value;
    }

    /**
     * A code that can be used to classify the transaction at the tax level for reporting or
     *                     tax return filing purposes. The code is generated by the Calculation Engine for each line item after
     *                     tax calculation. It can be used as a filter for reports or as an input for post-calculation Tax
     *                     Assist rules. For detailed information about the contents of the code, see the Supporting
     *                     Information section of the XML Integration Guide.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVertexTaxCode() {
        return vertexTaxCode;
    }

    /**
     * Sets the value of the vertexTaxCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getVertexTaxCode()
     */
    public void setVertexTaxCode(String value) {
        this.vertexTaxCode = value;
    }

    /**
     * A code that indicates the reason for the exception that was applied to this tax.
     *                     Note: For a tax with multiple tiers, O Series returns the reason code associated with the largest
     *                     basis amount. Note: To pass a standard (i.e., not user-defined) single-digit reason code, pad the
     *                     code to four digits. Refer to the Supporting Information section of the XML Integration Guide for
     *                     information on exemption and deduction reason codes.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCode() {
        return reasonCode;
    }

    /**
     * Sets the value of the reasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getReasonCode()
     */
    public void setReasonCode(String value) {
        this.reasonCode = value;
    }

    /**
     * Provides additional classification of the transaction for tax returns and reporting.
     *                     Codes are jurisdiction-specific. Note: For a tax with multiple tiers, O Series returns the filing
     *                     category code associated with the largest basis amount.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFilingCategoryCode() {
        return filingCategoryCode;
    }

    /**
     * Sets the value of the filingCategoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     * @see #getFilingCategoryCode()
     */
    public void setFilingCategoryCode(Integer value) {
        this.filingCategoryCode = value;
    }

    /**
     * Indicates whether or not the product is a service.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsService() {
        return isService;
    }

    /**
     * Sets the value of the isService property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #isIsService()
     */
    public void setIsService(Boolean value) {
        this.isService = value;
    }

    /**
     * A Vertex-defined classification of the applicable tax rule for returns filing
     *                     purposes. Possible values are: Luxury Rate, Standard Rate, Reduced Rate 1, Reduced Rate 2, Reduced
     *                     Rate 3, Reduced Rate 4, Reduced Rate 5, User Defined, Zero Rate, Outside the Scope.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateClassification() {
        return rateClassification;
    }

    /**
     * Sets the value of the rateClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getRateClassification()
     */
    public void setRateClassification(String value) {
        this.rateClassification = value;
    }

    /**
     * The party who is responsible for the sales tax. Note: Tax amounts with a value of
     *                     Seller cannot be charged to your customer and should NOT be written to the invoice.
     * 
     * @return
     *     possible object is
     *     {@link TaxCollectedFromPartyType }
     *     
     */
    public TaxCollectedFromPartyType getTaxCollectedFromParty() {
        return taxCollectedFromParty;
    }

    /**
     * Sets the value of the taxCollectedFromParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxCollectedFromPartyType }
     *     
     * @see #getTaxCollectedFromParty()
     */
    public void setTaxCollectedFromParty(TaxCollectedFromPartyType value) {
        this.taxCollectedFromParty = value;
    }

    /**
     * Specifies the applicable tax structure when the transaction includes a flat
     *                     fee or quantity-based fee. Valid values are
     *                     BRACKET, FLAT_TAX, QUANTITY, SINGLE_RATE, TIERED, QUANTITY_TIERED, QUANTITY_RATE_TIERED,
     *                     TIERED_MODIFIER, QUANTITY_TIERED_MODIFIER, QUANTITY_RATE_TIERED_MODIFIER, QUANTITY_TIERED_FLAT,
     *                     TIERED_FLAT and QUANTITY_RATE_TIERED_EQUIVALENT.
     * 
     * @return
     *     possible object is
     *     {@link TaxStructureCodeType }
     *     
     */
    public TaxStructureCodeType getTaxStructure() {
        return taxStructure;
    }

    /**
     * Sets the value of the taxStructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxStructureCodeType }
     *     
     * @see #getTaxStructure()
     */
    public void setTaxStructure(TaxStructureCodeType value) {
        this.taxStructure = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.w3.org/2001/XMLSchema>string">
     *       <attribute name="userDefined" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       <attribute name="impositionId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class AccumulateAsImposition {

        @XmlValue
        protected String value;
        /**
         * An identifier for user-defined imposition. This identifier is
         *                                         useful for troubleshooting. The default value indicates a Vertex-defined
         *                                         imposition.
         * 
         */
        @XmlAttribute(name = "userDefined")
        protected Boolean userDefined;
        /**
         * The Vertex internal identifier for the imposition.
         * 
         */
        @XmlAttribute(name = "impositionId")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger impositionId;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * An identifier for user-defined imposition. This identifier is
         *                                         useful for troubleshooting. The default value indicates a Vertex-defined
         *                                         imposition.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isUserDefined() {
            return userDefined;
        }

        /**
         * Sets the value of the userDefined property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         * @see #isUserDefined()
         */
        public void setUserDefined(Boolean value) {
            this.userDefined = value;
        }

        /**
         * The Vertex internal identifier for the imposition.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getImpositionId() {
            return impositionId;
        }

        /**
         * Sets the value of the impositionId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getImpositionId()
         */
        public void setImpositionId(BigInteger value) {
            this.impositionId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<urn:vertexinc:o-series:tps:9:0>JurisdictionType">
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AccumulateAsJurisdiction
        extends JurisdictionType
    {


    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.w3.org/2001/XMLSchema>string">
     *       <attribute name="userDefined" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class AccumulateAsLineType {

        @XmlValue
        protected String value;
        /**
         * A flag to indicate the accumulate as line type is defined by user.
         * 
         */
        @XmlAttribute(name = "userDefined")
        protected Boolean userDefined;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * A flag to indicate the accumulate as line type is defined by user.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isUserDefined() {
            if (userDefined == null) {
                return false;
            } else {
                return userDefined;
            }
        }

        /**
         * Sets the value of the userDefined property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         * @see #isUserDefined()
         */
        public void setUserDefined(Boolean value) {
            this.userDefined = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.w3.org/2001/XMLSchema>string">
     *       <attribute name="certificateType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class CertificateNumber {

        @XmlValue
        protected String value;
        /**
         * The certificate type associated with the line item tax.
         * 
         */
        @XmlAttribute(name = "certificateType")
        protected String certificateType;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * The certificate type associated with the line item tax.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCertificateType() {
            return certificateType;
        }

        /**
         * Sets the value of the certificateType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getCertificateType()
         */
        public void setCertificateType(String value) {
            this.certificateType = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element ref="{urn:vertexinc:o-series:tps:9:0}CurrencyConversion"/>
     *         <element name="FilingCalculatedTax" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
     *         <element name="FilingExempt" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
     *         <element name="FilingNonTaxable" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
     *         <element name="FilingTaxable" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
     *         <element name="FilingRecoverableAmount" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
     *         <element name="FilingUnrecoverableAmount" type="{urn:vertexinc:o-series:tps:9:0}AmountType" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "currencyConversion",
        "filingCalculatedTax",
        "filingExempt",
        "filingNonTaxable",
        "filingTaxable",
        "filingRecoverableAmount",
        "filingUnrecoverableAmount"
    })
    public static class FilingCurrencyAmounts {

        /**
         * The rate (multiplier) used for converting the transaction currency amount to the filing
         *                 currency amount. Pass in this value and the currency code (isoCurrencyCodeAlpha or isoCurrencyCodeNum)
         *                 to have filing currency calculated if your configuration parameters are set up to do so.
         * 
         */
        @XmlElement(name = "CurrencyConversion", required = true)
        protected CurrencyConversion currencyConversion;
        /**
         * The calculated tax amount for the line item, reported in the filing
         *                                     currency.
         * 
         */
        @XmlElement(name = "FilingCalculatedTax")
        protected BigDecimal filingCalculatedTax;
        /**
         * The exempt amount for the line item, reported in the filing
         *                                     currency.
         * 
         */
        @XmlElement(name = "FilingExempt")
        protected BigDecimal filingExempt;
        /**
         * The non-taxable amount for the line item, reported in the filing
         *                                     currency
         * 
         */
        @XmlElement(name = "FilingNonTaxable")
        protected BigDecimal filingNonTaxable;
        /**
         * The taxable amount for the line item, reported in the filing
         *                                     currency.
         * 
         */
        @XmlElement(name = "FilingTaxable")
        protected BigDecimal filingTaxable;
        /**
         * The recoverable amount for the VAT line item, reported in the filing
         *                                     currency.
         * 
         */
        @XmlElement(name = "FilingRecoverableAmount")
        protected BigDecimal filingRecoverableAmount;
        /**
         * The unrecoverable amount for the VAT line item, reported in the
         *                                     filing currency.
         * 
         */
        @XmlElement(name = "FilingUnrecoverableAmount")
        protected BigDecimal filingUnrecoverableAmount;

        /**
         * The rate (multiplier) used for converting the transaction currency amount to the filing
         *                 currency amount. Pass in this value and the currency code (isoCurrencyCodeAlpha or isoCurrencyCodeNum)
         *                 to have filing currency calculated if your configuration parameters are set up to do so.
         * 
         * @return
         *     possible object is
         *     {@link CurrencyConversion }
         *     
         */
        public CurrencyConversion getCurrencyConversion() {
            return currencyConversion;
        }

        /**
         * Sets the value of the currencyConversion property.
         * 
         * @param value
         *     allowed object is
         *     {@link CurrencyConversion }
         *     
         * @see #getCurrencyConversion()
         */
        public void setCurrencyConversion(CurrencyConversion value) {
            this.currencyConversion = value;
        }

        /**
         * The calculated tax amount for the line item, reported in the filing
         *                                     currency.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getFilingCalculatedTax() {
            return filingCalculatedTax;
        }

        /**
         * Sets the value of the filingCalculatedTax property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getFilingCalculatedTax()
         */
        public void setFilingCalculatedTax(BigDecimal value) {
            this.filingCalculatedTax = value;
        }

        /**
         * The exempt amount for the line item, reported in the filing
         *                                     currency.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getFilingExempt() {
            return filingExempt;
        }

        /**
         * Sets the value of the filingExempt property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getFilingExempt()
         */
        public void setFilingExempt(BigDecimal value) {
            this.filingExempt = value;
        }

        /**
         * The non-taxable amount for the line item, reported in the filing
         *                                     currency
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getFilingNonTaxable() {
            return filingNonTaxable;
        }

        /**
         * Sets the value of the filingNonTaxable property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getFilingNonTaxable()
         */
        public void setFilingNonTaxable(BigDecimal value) {
            this.filingNonTaxable = value;
        }

        /**
         * The taxable amount for the line item, reported in the filing
         *                                     currency.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getFilingTaxable() {
            return filingTaxable;
        }

        /**
         * Sets the value of the filingTaxable property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getFilingTaxable()
         */
        public void setFilingTaxable(BigDecimal value) {
            this.filingTaxable = value;
        }

        /**
         * The recoverable amount for the VAT line item, reported in the filing
         *                                     currency.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getFilingRecoverableAmount() {
            return filingRecoverableAmount;
        }

        /**
         * Sets the value of the filingRecoverableAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getFilingRecoverableAmount()
         */
        public void setFilingRecoverableAmount(BigDecimal value) {
            this.filingRecoverableAmount = value;
        }

        /**
         * The unrecoverable amount for the VAT line item, reported in the
         *                                     filing currency.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getFilingUnrecoverableAmount() {
            return filingUnrecoverableAmount;
        }

        /**
         * Sets the value of the filingUnrecoverableAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         * @see #getFilingUnrecoverableAmount()
         */
        public void setFilingUnrecoverableAmount(BigDecimal value) {
            this.filingUnrecoverableAmount = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<http://www.w3.org/2001/XMLSchema>string">
     *       <attribute name="userDefined" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       <attribute name="impositionId" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Imposition {

        @XmlValue
        protected String value;
        /**
         * An identifier for user-defined imposition. This identifier is
         *                                         useful for troubleshooting. The default value indicates a Vertex-defined
         *                                         imposition.
         * 
         */
        @XmlAttribute(name = "userDefined")
        protected Boolean userDefined;
        /**
         * The Vertex internal identifier for the imposition.
         * 
         */
        @XmlAttribute(name = "impositionId")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger impositionId;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * An identifier for user-defined imposition. This identifier is
         *                                         useful for troubleshooting. The default value indicates a Vertex-defined
         *                                         imposition.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isUserDefined() {
            return userDefined;
        }

        /**
         * Sets the value of the userDefined property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         * @see #isUserDefined()
         */
        public void setUserDefined(Boolean value) {
            this.userDefined = value;
        }

        /**
         * The Vertex internal identifier for the imposition.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getImpositionId() {
            return impositionId;
        }

        /**
         * Sets the value of the impositionId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         * @see #getImpositionId()
         */
        public void setImpositionId(BigInteger value) {
            this.impositionId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <simpleContent>
     *     <extension base="<urn:vertexinc:o-series:tps:9:0>JurisdictionType">
     *     </extension>
     *   </simpleContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Jurisdiction
        extends JurisdictionType
    {


    }

}
