//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Identifies the tax rule type.
 * 
 * <p>Java class for TaxRuleCodeType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="TaxRuleCodeType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     <enumeration value="TAXABILITY_RULE"/>
 *     <enumeration value="MAX_TAX_RULE"/>
 *     <enumeration value="TAX_BASIS_RULE"/>
 *     <enumeration value="RECOVERABILITY_RULE"/>
 *     <enumeration value="TAX_INCLUSION_RULE"/>
 *     <enumeration value="POST_CALCULATION_EVALUATION_RULE"/>
 *     <enumeration value="CREDIT_RULE"/>
 *     <enumeration value="BASIS_APPORTIONMENT_RULE"/>
 *     <enumeration value="INVOICE_TEXT_RULE"/>
 *     <enumeration value="TAX_RATE_ADJUSTMENT_RULE"/>
 *     <enumeration value="TAX_APPORTIONMENT_RULE"/>
 *     <enumeration value="TAX_ACCUMULATION_RULE"/>
 *     <enumeration value="REPORTING_BASIS_RULE"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "TaxRuleCodeType")
@XmlEnum
public enum TaxRuleCodeType {


    /**
     * Taxability Rule.
     * 
     */
    TAXABILITY_RULE,

    /**
     * Max Tax Rule.
     * 
     */
    MAX_TAX_RULE,

    /**
     * Tax Basis Rule.
     * 
     */
    TAX_BASIS_RULE,

    /**
     * Recoverability Rule.
     * 
     */
    RECOVERABILITY_RULE,

    /**
     * Tax Inclusion Rule.
     * 
     */
    TAX_INCLUSION_RULE,

    /**
     * Post Calculation Evaluation Rule.
     * 
     */
    POST_CALCULATION_EVALUATION_RULE,

    /**
     * Credit Rule.
     * 
     */
    CREDIT_RULE,

    /**
     * Basis Apportionment Rule.
     * 
     */
    BASIS_APPORTIONMENT_RULE,

    /**
     * Invoice Text Rule.
     * 
     */
    INVOICE_TEXT_RULE,

    /**
     * Tax Rate Adjustment Rule.
     * 
     */
    TAX_RATE_ADJUSTMENT_RULE,

    /**
     * Tax Apportionment Rule.
     * 
     */
    TAX_APPORTIONMENT_RULE,

    /**
     * Tax Accumulsation Rule.
     * 
     */
    TAX_ACCUMULATION_RULE,

    /**
     * Reporting Basis Rule.
     * 
     */
    REPORTING_BASIS_RULE;

    public String value() {
        return name();
    }

    public static TaxRuleCodeType fromValue(String v) {
        return valueOf(v);
    }

}
