//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="TaxRuleCurrencyConversionFactor" type="{urn:vertexinc:o-series:tps:9:0}TaxRuleCurrencyConversionFactorType" maxOccurs="unbounded"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "taxRuleCurrencyConversionFactor"
})
@XmlRootElement(name = "TaxRuleCurrencyConversionFactors")
public class TaxRuleCurrencyConversionFactors {

    /**
     * This element contains tax rule and currency conversion information used
     *                             during the tax calculation.
     * 
     */
    @XmlElement(name = "TaxRuleCurrencyConversionFactor", required = true)
    protected List<TaxRuleCurrencyConversionFactorType> taxRuleCurrencyConversionFactor;

    /**
     * This element contains tax rule and currency conversion information used
     *                             during the tax calculation.
     * 
     * Gets the value of the taxRuleCurrencyConversionFactor property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxRuleCurrencyConversionFactor property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getTaxRuleCurrencyConversionFactor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxRuleCurrencyConversionFactorType }
     * </p>
     * 
     * 
     * @return
     *     The value of the taxRuleCurrencyConversionFactor property.
     */
    public List<TaxRuleCurrencyConversionFactorType> getTaxRuleCurrencyConversionFactor() {
        if (taxRuleCurrencyConversionFactor == null) {
            taxRuleCurrencyConversionFactor = new ArrayList<>();
        }
        return this.taxRuleCurrencyConversionFactor;
    }

}
