//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.siteone.integration.webserviceclient.vertexclient;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Identifies the utility provider.
 * 
 * <p>Java class for UtilityProviderType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="UtilityProviderType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     <enumeration value="REGULATED_TAXPAYER"/>
 *     <enumeration value="UNREGULATED_TAXPAYER"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "UtilityProviderType")
@XmlEnum
public enum UtilityProviderType {

    REGULATED_TAXPAYER,
    UNREGULATED_TAXPAYER;

    public String value() {
        return name();
    }

    public static UtilityProviderType fromValue(String v) {
        return valueOf(v);
    }

}
